services:
  sonarr:
    container_name: sonarr
    image: ghcr.io/11notes/sonarr:4
    env_file: ../../.env
    hostname: sonarr
    read_only: true
    restart: unless-stopped
    environment:
      - TZ=${TZ} # Timezone to run the container under.
    networks:
      - gluetun
      - internal
    ports:
      - ${SONARR_WEBUI_PORT:-8989}:8989/tcp # Local Sonarr web interface.
    volumes:
      - ${DOWNLOADS_DIRECTORY}:/downloads # Root downloads path; needs to be writable by 1000:1000.
      - ${MEDIA_LIBRARY_DIRECTORY}:/library # Root media library path; needs to be writable by 1000:1000.
      - sonarr:/sonarr/etc # Sonarr configuration/data volume.
    depends_on:
      qbittorrent:
        condition: service_started # Wait for qBittorrent to become healthy before starting.
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=1000,gid=1000 # Required for read-only images.
