services:
  sonarr:
    container_name: sonarr
    image: ghcr.io/11notes/sonarr:4.0.15
    read_only: true
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - TZ=${TZ}
    networks:
      - frontend # Internal network for local web interface access.
      - gluetun # Gluetun VPN network.
      - media # Internal media network.
    ports:
      - ${SONARR_WEBUI_PORT:-8989}:8989/tcp # Web interface.
    volumes:
      - ${DOWNLOADS_DIRECTORY}:/downloads # Root downloads directory; needs to be writable by 1000:1000.
      - ${MEDIA_LIBRARY_DIRECTORY}:/library # Root media library directory; needs to be writable by 1000:1000.
      - sonarr:/sonarr/etc # Configuration/data volume.
    depends_on:
      qbittorrent:
        condition: service_healthy # Wait for download clients to become healthy before starting.
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=1000,gid=1000 # required for read-only image

networks:
  frontend:
    name: frontend-network
    driver: bridge
    enable_ipv6: false
    external: true
  gluetun:
    name: gluetun-network
    driver: bridge
    enable_ipv6: false
    external: true
  media:
    name: media-network
    driver: bridge
    enable_ipv6: false
    external: true

volumes:
  sonarr:
    name: sonarr-volume
    external: true
