---
services:
    ###############################################################################
    # Socket Proxy: Proxies the Docker Socket for increased security.             #
    ##############################################################################

    socket-proxy:
        image: ghcr.io/wollomatic/socket-proxy:1.9.0
        container_name: socket-proxy
        restart: unless-stopped
        hostname: socket-proxy
        read_only: true
        user: 65534:${DOCKER_GID} # Run as an arbitrary UID in the Docker group.
        cap_drop:
            - ALL # Drop default Docker capabilities.
        environment:
            SP_ALLOW_GET: '(/v1\..{1,2})?/(_ping|version|info|containers/(json|\w+/json|\w+/stats.*|\w+/logs.*)|images/\S+/json|networks(/.*)?|events(\?\S+)?)' # Required GET requests for certain containers.
            SP_ALLOW_POST: '(/v1\..{1,2})?/containers/\w+/(start|stop|restart)' # Allow container actions.
            SP_ALLOW_HEAD: '(/v1\..{1,2})?/(_ping)'
            SP_ALLOWFROM: "caddy,dozzle" # Only allow traffic from specified containers.
            SP_ALLOWHEALTHCHECK: "true" # Enables healthcheck support.
            SP_LISTENIP: "0.0.0.0" # Only listen on 0.0.0.0.
        healthcheck:
            interval: 10s
            test: ["CMD", "./healthcheck"]
            timeout: 5s
        networks:
            - socket-proxy
        ports:
            - 2375:2375/tcp # Socket proxy port.
        security_opt:
            - no-new-privileges:true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro # Host Docker socket mount.

networks:
    socket-proxy:
        driver: bridge
        enable_ipv6: false
        external: true # $ docker network create --ipv6=false socket-proxy-network
        internal: true # Isolates the network from the outside.
        name: socket-proxy-network # Internal-only network used only for Socket Proxy traffic.
