---
services:
  ###########################################################################
  # Socket Proxy: Proxy wrapper for the Docker socket for secure access.    #
  ###########################################################################

  socket-proxy:
    image: ghcr.io/11notes/socket-proxy:2.1.4
    container_name: socket-proxy
    env_file: ../../.env
    hostname: socket-proxy
    read_only: true
    user: "0:${DOCKER_GID}"
    restart: unless-stopped
    environment:
      DEBUG: true
      TZ: "${TZ}" # Local timezone to use.
    networks:
      - socket-proxy # Internal-only socket proxy network.
    volumes:
      - /var/run/docker.sock:/run/docker.sock:ro # Host Docker socket mount.
      - socket-proxy:/run/proxy # Docker socket proxy volume.
    cap_drop:
      - ALL
    cap_add:
      - CHOWN # Required to change ownership.
      - DAC_OVERRIDE # Required for user:0:docker_gid
      - SETGID # Required to drop to GID.
      - SETUID # Required to drop to UID.
    security_opt:
      - no-new-privileges:true

networks:
  socket-proxy:
    external: true # $ docker network create --internal=true socket-proxy-network
    internal: true # Isolates the network from the outside.
    name: socket-proxy-network # Internal-only network used only for Socket Proxy traffic.

volumes:
  socket-proxy:
    external: true
    name: socket-proxy-volume # $ docker volume create socket-proxy-volume
