services:
    socket-proxy:
        container_name: "socket-proxy"
        image: "ghcr.io/11notes/socket-proxy:2"
        read_only: true # Prevents write-access to the image.
        restart: "always" # Always keep the socket-proxy running.
        security_opt: ["no-new-privileges:true"] # Prevents privilege escalation.
        user: 0:${DOCKER_PGID} # Run as the local Docker user.
        environment:
            SOCKET_PROXY_GID: "${PGID}" # Group ID to run the container under.
            SOCKET_PROXY_UID: "${PUID}" # User ID to run the container under.
            TZ: "${TZ}" # Timezone to run the container under.
        ports:
            - "2375:2375/tcp" # Socket proxy networking.
        volumes:
            - "/run/docker.sock:/run/docker.sock:ro" # Read-only access to the primary Docker socket.
            - "socket-proxy:/run/proxy" # Socket proxy mount volume.

volumes:
    socket-proxy:
        external: true
        name: "socket-proxy-volume"
