services:
    socket-proxy:
        container_name: "socket-proxy"
        image: "lscr.io/linuxserver/socket-proxy:latest"
        hostname: "socket-proxy"
        read_only: "true"
        restart: unless-stopped
        security_opt: ["no-new-privileges:true"]
        environment:
            ALLOW_START: "1" # Allow starting containers.
            ALLOW_STOP: "1" # Allow stopping containers.
            ALLOW_RESTARTS: "1" # Allow restarting containers.
            AUTH: "0" # Disable auth endpoint.
            BUILD: "0" # Disable build endpoint.
            COMMIT: "0" # Disable commit endpoint.
            CONFIGS: "0" # Disable configs endpoint.
            CONTAINERS: "1" # Allow containers endpoint.
            DISABLE_IPV6: "1" # Disable IPV6 binding.
            DISTRIBUTION: "0" # Disable distribution endpoint.
            EVENTS: "1" # Allow event logging.
            EXEC: "0" # Disable exec endpoint.
            IMAGES: "0" # Disable images endpoint.
            INFO: "0" # Disable info endpoint.
            LOG_LEVEL: info # Use info logging level.
            NETWORKS: "1" # Allow networks endpoint.
            NODES: "1" # Enable nodes endpoint.
            PING: "1" # Enable ping endpoint.
            PLUGINS: "0" # Disable plugins endpoint.
            POST: "0" # Disable POST requests.
            SECRETS: "0" # Disable secrets endpoint.
            SERVICES: "1" # Allow services endpoint.
            SESSION: "0" # Disable session endpoint.
            SWARM: "1" # Enable swarm endpoint.
            SYSTEM: "0" # Disable system endpoint.
            TASKS: "0" # Disable tasks endpoint.
            TZ: "${TZ}" # Timezone to configure the container to use.
            VERSION: "1" # Enable version endpoint.
            VOLUMES: "0" # Disable volume endpoint.
        healthcheck:
            interval: "1m"
            retries: "3"
            start_period: "15s"
            test: ["CMD", "wget", "--spider", "http://127.0.0.1:2375/_ping"]
            timeout: "3s"
        networks:
            - "internal" # Internal-only traffic network.
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro # Read-only Docker socket mount.
        tmpfs: /run # Required for read_only image.

networks:
    internal:
        driver: "bridge"
        external: "true"
        name: "internal-network"
