---
services:
    ###############################################################################
    # Lidarr: Music manager, organizer, and PVR.                                  #
    ##############################################################################

    lidarr:
        image: ghcr.io/hotio/lidarr:testing # use testing until Lidarr fixes their shit
        container_name: lidarr
        hostname: lidarr
        restart: unless-stopped
        environment:
            TZ: "${TZ}" # Configures the timezone to use.
            PGID: "${PGID}" # Local group to run as.
            PUID: "${PUID}" # Local user to run as.
            UMASK: "${UMASK}" # Umask to apply to newly created files.
        healthcheck:
            interval: 1m
            test: "curl -f http://127.0.0.1:8686/ping || exit 1"
        labels:
            caddy: "lidarr.${INTERNAL_DOMAIN}" # Reverse proxy to the internal domain.
            caddy.import: "internal lidarr:8686" # Reverse proxy internal traffic.
            caddy.tls.ca: "https://acme.zerossl.com/v2/DV90" # Use ZeroSSL for certificates.
            caddy.tls.dns: "cloudflare $CLOUDFLARE_API_TOKEN" # Use Cloudflare for DNS challenges.
            caddy.tls.protocols: "tls1.3" # Require TLS 1.3.
        networks:
            - gluetun
        ports:
            - ${LIDARR_PORT:-8686}:8686/tcp # Web interface.
        security_opt:
            - no-new-privileges:true
        volumes:
            - downloads:/downloads
            - media-library:/library
            - lidarr:/config
networks:
    gluetun:
        driver: bridge
        enable_ipv6: false
        external: true
        name: gluetun-network # $ docker network create --ipv6=false gluetun-network

volumes:
    lidarr:
        external: true
        name: lidarr-volume # $ docker volume create lidarr-volume
    downloads:
        name: downloads-volume
        driver_opts:
            device: "${DOWNLOADS_PATH}" # Root path to store downloaded files into.
            o: bind
            type: none
    media-library:
        name: media-library-volume
        driver_opts:
            device: "${MEDIA_LIBRARY_PATH}" # Root path to the media library.
            o: bind
            type: none
