---
services:
    ###############################################################################
    # Lidarr: Music manager, organizer, and PVR.                                  #
    ##############################################################################

    lidarr:
        image: blampe/lidarr:latest # lidarr is bad
        container_name: lidarr
        hostname: lidarr
        restart: unless-stopped
        environment:
            TZ: "${TZ}" # Configures the timezone to use.
            PGID: "${PGID}" # Local group to run as.
            PUID: "${PUID}" # Local user to run as.
            UMASK: "${UMASK}" # Umask to apply to newly created files.
        healthcheck:
            interval: 1m
            test: "curl -f http://127.0.0.1:8686/ping || exit 1"
        labels:
            caddy: "lidarr.${INTERNAL_DOMAIN}" # Reverse proxy to the internal domain.
            caddy.import: "internal lidarr:8686" # Reverse proxy internal traffic.
            caddy.tls.ca: "https://acme.zerossl.com/v2/DV90" # Use ZeroSSL for certificates.
            caddy.tls.dns: "cloudflare $CLOUDFLARE_API_TOKEN" # Use Cloudflare for DNS challenges.
            caddy.tls.protocols: "tls1.3" # Require TLS 1.3.
        networks:
            - caddy
            - gluetun
        ports:
            - ${LIDARR_PORT:-8686}:8686/tcp # Web interface.
        security_opt:
            - no-new-privileges:true
        volumes:
            - downloads:/downloads
            - media-library:/library
            - lidarr:/config

    slskd:
        image: slskd/slskd:latest
        container_name: slskd
        network_mode: service:gluetun # Route all traffic thru Gluetun.
        restart: unless-stopped
        user: ${PUID}:${PGID}
        depends_on:
            gluetun:
                condition: service_healthy
                restart: true
        environment:
            SLSKD_REMOTE_CONFIGURATION: "true" # Allows configuring settings through the web interface.
            SLSKD_UMASK: "${UMASK}" # Configures the umask to set on newly created files.
            TZ: "${TZ}" # Configures the timezone to use.
        labels:
            caddy: "soulseek.${INTERNAL_DOMAIN}" # Reverse proxy to the internal domain.
            caddy.import: "internal gluetun:5030" # Reverse proxy internal traffic.
            caddy.tls.ca: "https://acme.zerossl.com/v2/DV90" # Use ZeroSSL for certificates.
            caddy.tls.dns: "cloudflare $CLOUDFLARE_API_TOKEN" # Use Cloudflare for DNS challenges.
            caddy.tls.protocols: "tls1.3" # Require TLS 1.3.
        security_opt:
            - no-new-privileges:true
        volumes:
            - slskd:/app
            - soulseek-downloads:/downloads

    soularr:
        image: mrusse08/soularr:latest
        container_name: soularr
        network_mode: service:gluetun # Route all traffic thru Gluetun.
        restart: unless-stopped
        user: ${PUID}:${PGID}
        depends_on:
            gluetun:
                condition: service_healthy
                restart: true
            lidarr:
                condition: service_healthy
                restart: true
            slskd:
                condition: service_healthy
                restart: true
        environment:
            TZ: "${TZ}" # Configures the timezone to use.
        security_opt:
            - no-new-privileges:true
        volumes:
            - soularr:/data
            - soulseek-downloads:/downloads

networks:
    caddy:
        driver: bridge
        enable_ipv6: false
        external: true
        name: caddy-network # $ docker network create --ipv6=false caddy-network
    gluetun:
        driver: bridge
        enable_ipv6: false
        external: true
        name: gluetun-network # $ docker network create --ipv6=false gluetun-network

volumes:
    lidarr:
        external: true
        name: lidarr-volume # $ docker volume create lidarr-volume
    slskd:
        external: true
        name: slskd-volume # $ docker volume create slskd-volume
    downloads:
        name: downloads-volume
        driver_opts:
            device: "${DOWNLOADS_PATH}" # Root path to store downloaded files into.
            o: bind
            type: none
    media-library:
        name: media-library-volume
        driver_opts:
            device: "${MEDIA_LIBRARY_PATH}" # Root path to the media library.
            o: bind
            type: none
    soularr:
        name: soularr-volume
        driver_opts:
            device: "${SOULARR_DATA_PATH}" # Root path to store Soularr data.
            o: bind
            type: none
    soulseek-downloads:
        name: soulseek-downloads-volume
        driver_opts:
            device: "${DOWNLOADS_PATH}/soulseek" # Root path to store downloaded soulseek files into.
            o: bind
            type: none
