---
# Default environment variables.
x-defaults-environment: &defaults-environment
  PGID: "${PGID}" # Local group to run as.
  PUID: "${PUID}" # Local user to run as.
  TZ: "${TZ}" # Configures the timezone to use.
  UMASK: "${UMASK}" # Default umask to apply to newly created files.

# Default container options.
x-defaults: &defaults
  restart: unless-stopped
  environment: *defaults-environment
  networks:
    - caddy
    - gluetun
  cap_drop:
    - AUDIT_WRITE
    - MKNOD
    - SYS_CHROOT
  security_opt:
    - no-new-privileges:true

services:
  ###########################################################################
  # Lidarr: Music manager, organizer, and PVR - https://lidarr.audio        #
  ###########################################################################

  lidarr:
    <<: *defaults
    image: ghcr.io/hotio/lidarr:pr-plugins-2.14.2.4786
    container_name: lidarr
    hostname: lidarr
    expose:
      - 8686/tcp # Web interface.
    volumes:
      - downloads:/downloads
      - lidarr:/config
      - media-library:/library
    healthcheck:
      test: "curl -f http://127.0.0.1:8686/health || exit 1"

  ###########################################################################
  # Radarr: Movie manager, organizer, and PVR - https://radarr.video        #
  ###########################################################################

  radarr:
    <<: *defaults
    image: ghcr.io/hotio/radarr:release-5.27.5.10198
    container_name: radarr
    hostname: radarr
    restart: unless-stopped
    expose:
      - 7878/tcp # Web interface.
    volumes:
      - ./scripts:/scripts
      - downloads:/downloads
      - media-library:/library
      - radarr:/config
    healthcheck:
      test: "curl -f http://127.0.0.1:7878/health || exit 1"

  ###########################################################################
  # Sonarr: Music manager, organizer, and PVR - https://sonarr.tv           #
  ###########################################################################

  sonarr:
    <<: *defaults
    image: ghcr.io/hotio/sonarr:release-4.0.15.2941
    container_name: sonarr
    hostname: sonarr
    expose:
      - 8989/tcp
    volumes:
      - downloads:/downloads
      - media-library:/library
      - sonarr:/config
    healthcheck:
      test: "curl -f http://127.0.0.1:8989/health || exit 1"

  ###########################################################################
  # Profilarr: Config management for 'ARR apps - https://dictionarry.dev    #
  ###########################################################################

  profilarr:
    <<: *defaults
    image: santiagosayshey/profilarr:v1.1.3
    container_name: profilarr
    hostname: profilarr
    expose:
      - 6868/tcp
    volumes:
      - profilarr:/config

  ###########################################################################
  # Huntarr: Automated media upgrade tool - http://huntarr.io/              #
  ###########################################################################

  huntarr:
    <<: *defaults
    image: ghcr.io/plexguide/huntarr:8.2.10
    container_name: huntarr
    hostname: huntarr
    read_only: true
    expose:
      - 9705/tcp
    volumes:
      - huntarr:/config
    tmpfs:
      - "/tmp" # Required for read-only image.

  ###########################################################################
  # Cleanuparr: PVR cleanup tool - https://cleanuparr.github.io/Cleanuparr  #
  ###########################################################################

  cleanuparr:
    <<: *defaults
    image: ghcr.io/cleanuparr/cleanuparr:2.3.3
    container_name: cleanuparr
    hostname: cleanuparr
    expose:
      - 11011/tcp
    volumes:
      - cleanuparr:/config
    healthcheck:
      test: "curl -f http://127.0.0.1:11011/health || exit 1"

  ###########################################################################
  # Unpackerr: Auto-extract compressed downloads - https://unpackerr.zip   #
  ###########################################################################

  unpackerr:
    <<: *defaults
    image: ghcr.io/unpackerr/unpackerr:0.14.5
    container_name: unpackerr
    hostname: unpackerr
    read_only: true
    user: ${PUID}:${PGID}
    environment:
      <<: *defaults-environment
      UN_LOG_FILE: "/downloads/unpackerr.log" # Log file location.
      UN_RADARR_0_API_KEY: "${RADARR_API_KEY}" # Radarr API key.
      UN_RADARR_0_URL: "http://radarr:7878" # Primary Radarr URL.
      UN_SONARR_0_API_KEY: "${SONARR_API_KEY}" # Sonarr API key.
      UN_SONARR_0_URL: "http://sonarr:8989" # Primary Sonarr URL.
    tmpfs:
      - "/tmp" # Required for read-only image.
    volumes:
      - downloads:/downloads

networks:
  caddy:
    external: true
    name: caddy-network # $ docker network create caddy-network
  gluetun:
    external: true
    name: gluetun-network # $ docker network create gluetun-network

volumes:
  cleanuparr:
    external: true
    name: cleanuparr-volume # $ docker volume create cleanuparr-volume
  huntarr:
    external: true
    name: huntarr-volume # $ docker volume create huntarr-volume
  lidarr:
    external: true
    name: lidarr-volume # $ docker volume create lidarr-volume
  profilarr:
    external: true
    name: profilarr-volume # $ docker volume create profilarr-volume
  radarr:
    external: true
    name: radarr-volume # $ docker volume create radarr-volume
  sonarr:
    external: true
    name: sonarr-volume # $ docker volume create sonarr-volume
  downloads:
    name: downloads-bind
    driver_opts:
      device: "${DOWNLOADS_PATH}" # Root path to store downloaded files into.
      o: bind
      type: none
  media-library:
    name: media-library-bind
    driver_opts:
      device: "${MEDIA_LIBRARY_PATH}" # Root path to the media library.
      o: bind
      type: none
