services:
    qbittorrent:
        container_name: qbittorrent
        image: ghcr.io/11notes/qbittorrent:5
        command: --profile=/opt --confirm-legal-notice # Shuts the annoying legal notice up.
        network_mode: service:gluetun # Route all networking through Gluetun.
        read_only: true
        restart: unless-stopped
        environment:
            TZ: ${TZ}
        volumes:
            - downloads:/downloads # Root downloads volume.
            - qbittorrent:/qbittorrent/etc # qBittorrent configuration volume.
            - qbittorrent:/qbittorrent/var # qBittorrent database volume.
        depends_on:
            gluetun:
                condition: service_healthy # Require Gluetun to be healthy before connecting.
                restart: true
        security_opt:
            - no-new-privileges:true

volumes:
    qbittorrent:
        name: qbittorrent-volume
        external: true
