services:
    qbittorrent:
        container_name: "qbittorrent"
        image: "lscr.io/linuxserver/qbittorrent:latest"
        network_mode: "service:gluetun" # Route all networking through Gluetun.
        restart: "unless-stopped"
        security_opt: ["no-new-privileges:true"]
        depends_on:
            gluetun:
                condition: "service_healthy" # Require Gluetun to be healthy before connecting.
                restart: "true"
        environment:
            DOCKER_MODS: "ghcr.io/gabe565/linuxserver-mod-vuetorrent" # Auto-install Vuetorrent.
            PGID: "${PGID}" # Group ID to run the container as.
            PUID: "${PUID}" # User ID to run the container as.
            TZ: "${TZ}" # Timezone to configure the container to use.
            UMASK: "${UMASK}" # Default umask permissions to apply to newly created files.
            WEBUI_PORT: "${QBITTORRENT_PORT:-8080}" # Configures the web interface port.
        healthcheck:
            interval: "1m"
            retries: "3"
            start_period: "1m"
            test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/"]
            timeout: "3s"
        volumes:
            - "gluetun:/tmp/gluetun" # Gluetun data.
            - "downloads:/downloads" # Root downloads volume.
            - "qbittorrent:/config" # qBittorrent configuration volume.

    qbittorrent-port-manager:
        container_name: qbittorrent-port-manager
        image: jopiermeier/gluetun-qbittorrent-port-manager:latest
        network_mode: "service:gluetun" # Route all networking through Gluetun.
        restart: "unless-stopped"
        security_opt: ["no-new-privileges:true"]
        read_only: true
        depends_on:
            gluetun:
                condition: "service_healthy" # Require Gluetun to be healthy before connecting.
                restart: "true"
            qbittorrent:
                condition: "service_started" # Require qBittorrent to be started before connecting.
                restart: "true"
        environment:
            QBITTORRENT_USER: "${QBITTORRENT_USER}"
            QBITTORRENT_PASS: "${QBITTORRENT_PASS}"
        volumes:
            - "gluetun:/tmp/gluetun" # Gluetun data.

volumes:
    downloads:
        name: "downloads-volume"
        driver_opts:
            device: "${DOWNLOADS_PATH}" # Root downloads directory path.
            o: "bind"
            type: "none"
    qbittorrent:
        name: "qbittorrent-volume"
        external: "true"
