---
services:
    ###########################################################################
    # OpenCloud: Self-hosted cloud storage service - https://opencloud.eu/en  #
    ###########################################################################

    opencloud:
        image: opencloudeu/opencloud-rolling:3.5.0
        container_name: opencloud
        entrypoint: /bin/sh
        hostname: opencloud
        restart: unless-stopped
        read_only: true
        user: "${PUID}:${PGID}"
        command:
            ["-c", "opencloud init --insecure true || true; opencloud server"]
        environment:
            FRONTEND_ARCHIVER_MAX_SIZE: "10000000000" # Max size of 10GB for web archives.
            IDM_ADMIN_PASSWORD: "${OPENCLOUD_ADMIN_PASSWORD}" # Configures the initial admin password.
            IDM_CREATE_DEMO_USERS: "false" # Do not create demo users.
            NOTIFICATIONS_SMTP_ENCRYPTION: "${SMTP_TRANSPORT_ENCRYPTION}" # Type of encryption to use or something idk.
            NOTIFICATIONS_SMTP_HOST: "${SMTP_HOST}" # External SMTP host URL to connect to.
            NOTIFICATIONS_SMTP_INSECURE: "${SMTP_INSECURE}" # If enabled, allows insecure connections to the external SMTP server.
            NOTIFICATIONS_SMTP_PASSWORD: "${SMTP_PASSWORD}" # External SMTP email account password to login with.
            NOTIFICATIONS_SMTP_PORT: "${SMTP_PORT}" # External SMTP port to connect to.
            NOTIFICATIONS_SMTP_SENDER: "OpenCloud <${SMTP_SENDER}>" # External SMTP address for sending email notifications.
            NOTIFICATIONS_SMTP_USERNAME: "${SMTP_USERNAME}" # External SMTP email account username to login with.
            OC_ADD_RUN_SERVICES: "notifications" # Additional services to start.
            OC_INSECURE: "false" # Do not run in insecure mode.
            OC_LOG_COLOR: "true" # Log in color.
            OC_LOG_LEVEL: "info" # Log at the info level.
            OC_LOG_PRETTY: "true" # Use pretty logs.
            OC_SHARING_PUBLIC_SHARE_MUST_HAVE_PASSWORD: "false" # Allow public shares without passwords.
            OC_SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD: "true" # Writable public shares must have passwords.
            OC_URL: "https://${OPENCLOUD_URL}" # Configures the OpenCloud URL.
            PROXY_TLS: "false" # Do not use SSL between the reverse proxy and OpenCloud.
            TZ: "${TZ}" # Configures the timezone to use.
        expose:
            - 9200/tcp # Web interface.
        networks:
            - caddy
        tmpfs:
            - "/tmp:uid=${PUID},gid=${PGID}" # Required for read-only image.
        volumes:
            - opencloud-config:/etc/opencloud
            - opencloud-data:/var/lib/opencloud
        cap_drop:
            - ALL
        extra_hosts:
            - "${OPENCLOUD_URL}:host-gateway" # Required for resolving the external URL.
        healthcheck:
            test: "wget --spider http://127.0.0.1:9200 || exit 1"
        security_opt:
            - no-new-privileges:true

networks:
    caddy:
        external: true
        name: caddy-network # $ docker network create caddy-network

volumes:
    opencloud-config:
        name: opencloud-config-bind
        driver_opts:
            device: "${APPDATA_PATH}/opencloud/config" # Root path to store OpenCloud config data.
            o: bind
            type: none
    opencloud-data:
        name: opencloud-data-bind
        driver_opts:
            device: "${APPDATA_PATH}/opencloud/data" # Root path to store OpenCloud user data.
            o: bind
            type: none
