services:
  caddy:
    container_name: caddy
    image: ghcr.io/homeall/caddy-reverse-proxy-cloudflare:2025.08.19
    env_file: ../../.env
    hostname: caddy
    restart: unless-stopped
    environment:
      - CADDY_INGRESS_NETWORKS=external # Only proxy traffic from the external network.
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN} # A scoped Cloudflare account token with DNS Zone edit permissions.
      - TZ=${TZ} # Timezone to run the container under.
    networks:
      - external
      - internal
    ports:
      - 80:80 # HTTP traffic.
      - 443:443 # HTTPS traffic.
      - 443:443/udp # HTTPS/3 traffic.
    volumes:
      - socket-proxy:/var/run # Docker socket proxy mount.
      - caddy:/data # Caddy configuration/data volume.
    depends_on:
      socket-proxy:
        condition: service_healthy
    labels:
      caddy.acme_dns: cloudflare ${CLOUDFLARE_API_TOKEN} # Use Cloudflare for TLS DNS challenges instead of LE.
      caddy.email: ${ACME_EMAIL} # Email to use for public ACME challenges.
    security_opt:
      - no-new-privileges:true
