services:
  caddy:
    container_name: caddy
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    cap_add: [NET_BIND_SERVICE] # Port binding.
    cap_drop: [ALL]
    networks: [external]
    read_only: true
    restart: unless-stopped
    environment:
      - CADDY_INGRESS_NETWORKS=external
      - CADDY_GLOBAL_OPTIONS=config.root /data
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy:/data
      - type: tmpfs
        target: /tmp
