services:
  caddy:
    container_name: caddy
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 80:80
      - 443:443
    environment:
      CADDY_INGRESS_NETWORKS: external
    networks:
      - external
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy:/data

networks:
  external:
    external: true

volumes:
  caddy:
    external: true
