include:
  - ./apps/caddy/compose.yml # caddy-docker-proxy: Reverse proxy
  - ./apps/cloudflare-ddns/compose.yml # cloudflare-ddns: Dynamic DNS automation for Cloudflare
  - ./apps/jellyfin/compose.yml # Jellyfin: Media server

networks:
  external: # External network for non-VPN traffic (Caddy, Jellyfin)
    driver: bridge
    name: external-network

volumes:
  jellyfin:
    name: jellyfin-volume
  caddy:
    name: caddy-volume
