include:
  - ./apps/caddy/compose.yml
  - ./apps/cloudflare-ddns/compose.yml
  - ./apps/gluetun/compose.yml
  - ./apps/jellyfin/compose.yml
  - ./apps/nextcloud/compose.yml
  - ./apps/qbittorrent/compose.yml

networks:
  external:
    driver: bridge
    name: external-network
  nextcloud-internal:
    driver: bridge
    name: nextcloud-internal-network

volumes:
  caddy:
    name: caddy-volume
  gluetun:
    name: gluetun-volume
  jellyfin:
    name: jellyfin-volume
  jellyfin-dpkeys:
    name: jellyfin-dpkeys-volume
  qbittorrent:
    name: qbittorrent-volume
  nextcloud:
    name: nextcloud-volume
  nextcloud-mariadb:
    name: nextcloud-mariadb-volume
  nextcloud-redis:
    name: nextcloud-redis-volume
