include:
    - "./services/bazarr/compose.yml" # Subtitle manager.
    - "./services/bookshelf/compose.yml" # Book manager and PVR (fork of Readarr).
    - "./services/caddy/compose.yml" # Reverse proxy and web server.
    - "./services/cleanuparr/compose.yml" # 'ARR cleanup tool.
    - "./services/cloudflare-ddns/compose.yml" # Dynamic DNS updates to Cloudflare.
    - "./services/deemix/compose.yml" # Deezer download client.
    - "./services/flaresolverr/compose.yml" # Bypass Cloudflare and DDoS-Guard.
    - "./services/gluetun/compose.yml" # VPN client.
    - "./services/jellyfin/compose.yml" # Media server.
    - "./services/lidarr/compose.yml" # Music manager and PVR.
    - "./services/mam-ip-helper/compose.yml" # Automatically update linked MyAnonaMouse IP.
    - "./services/picard/compose.yml" # Music tagger; web version.
    - "./services/profilarr/compose.yml" # 'ARR profile manager.
    - "./services/prowlarr/compose.yml" # 'ARR indexer manager.
    - "./services/qbittorrent/compose.yml" # BitTorrent client.
    - "./services/radarr/compose.yml" # Movie manager and PVR.
    - "./services/socket-proxy/compose.yml" # Proxy wrapper around the Docker socket for security.
    - "./services/sonarr/compose.yml" # Anime/TV series manager and PVR.
    - "./services/syncthing/compose.yml" # Cross-device file synchronization.
    - "./services/thelounge/compose.yml" # IRC client.

networks:
    gluetun: # Network used for VPN traffic.
        driver: "bridge"
        external: true
        name: "gluetun-network"
    external: # Network used for outbound reverse proxied traffic.
        driver: "bridge"
        external: true
        name: "external-network"
    frontend: # Network used for internal frontends.
        driver: "bridge"
        external: true
        name: "frontend-network"
    media: # Network used for shared media stack applications.
        driver: "bridge"
        external: true
        name: "media-network"

volumes:
    downloads: # Root path to the downloads directory.
        name: "downloads-volume"
        driver_opts:
            device: "${DOWNLOADS_PATH}"
            o: "bind"
            type: "none"
    media-library: # Root path to the media library directory.
        name: "media-library-volume"
        driver_opts:
            device: "${MEDIA_LIBRARY_PATH}"
            o: "bind"
            type: "none"
