include:
  - ./apps/beszel/compose.yml # Caddy: Web server and reverse proxy.
  - ./apps/caddy/compose.yml # Caddy: Web server and reverse proxy.
  - ./apps/cloudflare-ddns/compose.yml # Cloudflare-DDNS: Dynamic DNS record updating to Cloudflare.
  - ./apps/gluetun/compose.yml # Gluetun: VPN client.
  - ./apps/jellyfin/compose.yml # Jellyfin: Media server.
  - ./apps/lidarr/compose.yml # Lidarr: PVR for music.
  - ./apps/qbittorrent/compose.yml # qBittorrent: BitTorrent client.
  - ./apps/radarr/compose.yml # Radarr: PVR for movies.
  - ./apps/socket-proxy/compose.yml # Docker-Socket-Proxy: Docker socket proxy
  - ./apps/sonarr/compose.yml # Sonarr: PVR for anime/tv.
  - ./apps/syncthing/compose.yml # Syncthing: Cross-device file synchronization.

networks:
  caddy:
    name: caddy-network # External Caddy/reverse proxy network.
    driver: bridge
    enable_ipv6: false
    external: true
  frontend:
    name: frontend-network # Internal network for local web interfaces.
    driver: bridge
    enable_ipv6: false
    external: true
  gluetun:
    name: gluetun-network # Gluetun VPN network.
    driver: bridge
    enable_ipv6: false
    external: true
  media:
    name: media-network # Internal media network.
    driver: bridge
    enable_ipv6: false
    external: true

volumes:
  beszel:
    name: beszel-volume # Beszel configuration and data volume
    external: true
  beszel-socket:
    name: beszel-socket-volume # Beszel socket volume.
    external: true
  caddy:
    name: caddy-volume # Caddy certificate and configuration data volume.
    external: true
  gluetun:
    name: gluetun-volume # Gluetun configuration volume.
    external: true
  jellyfin:
    name: jellyfin-volume # Jellyfin configuration volume.
    external: true
  jellyfin-cache:
    name: jellyfin-cache-volume # Jellyfin cache volume.
    external: true
  lidarr:
    name: lidarr-volume # Lidarr configuration volume.
    external: true
  qbittorrent:
    name: qbittorrent-volume # qBittorrent configuration volume.
    external: true
  radarr:
    name: radarr-volume # Radarr configuration volume.
    external: true
  socket-proxy:
    name: socket-proxy-volume # Docker socket proxy volume.
    external: true
  sonarr:
    name: sonarr-volume # Sonarr configuration volume.
    external: true
