include:
  # Media
  - ./jellyfin/compose.yml # Jellyfin (Home Media Server)

  # Networking
  - ./cloudflare-ddns/compose.yml # cloudflare-ddns (Automatic DNS record updating)

networks:
  external: # External network (Jellyfin, NextCloud)
    driver: bridge
    name: external-network

volumes:
  jellyfin: # Jellyfin volume
    name: jellyfin-volume
