include:
    - ./services/external-apps/compose.yml # External apps stack.
    - ./services/infrastructure/compose.yml # Infrastructure  stack.
    - ./services/media-management/compose.yml # Media management stack.
