include:
  - ./apps/caddy/compose.yml # caddy-docker-proxy: Reverse proxy
  - ./apps/cloudflare-ddns/compose.yml # cloudflare-ddns: Dynamic DNS automation for Cloudflare
  - ./apps/jellyfin/compose.yml # Jellyfin: Media server
  - ./apps/nextcloud/compose.yml # Nextcloud: Cloud storage

networks:
  external: # External network for non-VPN traffic.
    driver: bridge
    name: external-network

volumes:
  jellyfin:
    name: jellyfin-volume # Jellyfin config volume.
  jellyfin-dpkeys:
    name: jellyfin-dpkeys # Jellyfin dpkeys volume.
  caddy:
    name: caddy-volume # Caddy data volume.
  nextcloud:
    name: nextcloud-volume # Nextcloud config volume.
  nextcloud-mariadb:
    name: nextcloud-mariadb-volume # Nextcloud's MariaDB volume.
  nextcloud-redis:
    name: nextcloud-redis-volume # Nextcloud's Redis volume.
