services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    env_file: ../../.env
    group_add: ["989"] # add 989 to perms to allow access to /dev/dri.
    networks: [external]
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    user: ${PUID}:${PGID}
    devices:
      - /dev/dri/renderD129:/dev/dri/renderD129
      - /dev/dri/card1:/dev/dri/card1
    environment:
      - LIBVA_DRIVER_NAME=radeonsi
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 60s
      test: ["CMD", "curl", "-f", "http://localhost:8096/health"]
      timeout: 10s
    labels:
      caddy: ${URL_PUBLISHED_JELLYFIN}
      caddy.header: Strict-Transport-Security "max-age=15552000; includeSubDomains"
      caddy.reverse_proxy: jellyfin:8096
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    ports:
      - 1900:1900/udp
      - 7359:7359/udp
    volumes:
      - ${PATH_MEDIA_LIBRARY}:/media
      - jellyfin-dpkeys:/root/.aspnet/DataProtection-Keys
      - jellyfin:/config
