# apps/jellyfin/compose.yml
services:
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:latest
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    devices:
      - /dev/dri:/dev/dri
    env_file:
      - ../../.env
    environment:
      JELLYFIN_PublishedServerUrl: "https://${URL_PUBLISHED_JELLYFIN}"
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 60s
      test: ["CMD", "curl", "-f", "http://localhost:8096/health"]
      timeout: 10s
    labels:
      caddy: ${URL_PUBLISHED_JELLYFIN}
      caddy.reverse_proxy: "jellyfin:8096"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    networks:
      - external
    ports:
      - 7359:7359/udp
    volumes:
      - ${PATH_MEDIA_LIBRARY}:/data
      - jellyfin:/config
