services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    user: ${PUID}:${PGID}
    devices:
      - /dev/dri:/dev/dri
    env_file:
      - ../../.env
    environment:
      - JELLYFIN_PublishedServerUrl=https://${URL_PUBLISHED_JELLYFIN}
      - LIBVA_DRIVER_NAME=radeonsi
    group_add:
      - 989 # required for render permissions
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 60s
      test: ["CMD", "curl", "-f", "http://localhost:8096/health"]
      timeout: 10s
    labels:
      caddy: ${URL_PUBLISHED_JELLYFIN}
      caddy.header: Strict-Transport-Security "max-age=15552000; includeSubDomains"
      caddy.reverse_proxy: jellyfin:8096
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      - external
    ports:
      - 1900:1900/udp
      - 7359:7359/udp
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${PATH_MEDIA_LIBRARY}:/media
      - jellyfin-dpkeys:/root/.aspnet/DataProtection-Keys
      - jellyfin:/config
