services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    env_file: ../../.env
    networks: [caddy] # Connect to the Caddy network for external access.
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    devices:
      - /dev/dri:/dev/dri # Video device access; /dev/dri/renderD128 is iGPU, /dev/dri/renderD129 is usually dGPU for VAAPI.
    environment:
      - DOCKER_MODS=linuxserver/mods:jellyfin-amd:latest|ghcr.io/intro-skipper/intro-skipper-docker-mod:latest # Enable latest mesa; add intro skipper.
      - JELLYFIN_PublishedServerUrl=https://${PUBLISHED_JELLYFIN_URL} # Sets the published server URL to the external one.
      - PGID=${PGID} # Group ID to run under.
      - PUID=${PUID} # User ID to run under.
      - TZ=${TZ} # Timezone to run with.
      - UMASK=${UMASK} # Default umask permissions to set.
    healthcheck:
      interval: 5m
      retries: 3
      start_period: 1m
      test: ["CMD", "curl", "-f", "http://localhost:8096/health"]
      timeout: 10s
    labels:
      caddy: ${PUBLISHED_JELLYFIN_URL} # Tells Caddy to reverse-proxy to the external Jellyfin URL.
      caddy.reverse_proxy: jellyfin:8096 # Tells Caddy to reverse-proxy Jellyfin traffic.
      caddy.tls.ca: https://acme.zerossl.com/v2/DV90 # Use ZeroSSL.
      caddy.tls.dns: cloudflare $CLOUDFLARE_API_TOKEN # Use Cloudflare as the DNS resolver.
      caddy.tls.protocols: tls1.3 # Enforce TLS 1.3.
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    volumes:
      - ${ROOT_MEDIA_LIBRARY_DIRECTORY}/anime-movies:/anime-movies # Path to the anime movies library.
      - ${ROOT_MEDIA_LIBRARY_DIRECTORY}/anime:/anime # Path to the anime library.
      - ${ROOT_MEDIA_LIBRARY_DIRECTORY}/movies:/movies # Path to the movies library.
      - ${ROOT_MEDIA_LIBRARY_DIRECTORY}/music:/music # Path to the music library.
      - ${ROOT_MEDIA_LIBRARY_DIRECTORY}/tv:/tv # Path to the TV library.
      - jellyfin:/config # Jellyfin data volume.
