services:
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:latest
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    devices:
      - /dev/dri:/dev/dri # Hardware acceleration device mount
    env_file:
      - ../../.env
      - .env
    environment:
      - PGID=${PGID} # PGID to run as
      - PUID=${PUID} # PUID to run as
      - TZ=${TZ} # Timezone to use
    labels:
      caddy: ${JELLYFIN_PUBLISHED_URL} # Tell caddy to reverse proxy container to JELLYFIN_PUBLISHED_URL
      caddy.reverse_proxy: "{{upstreams ${JELLYFIN_HTTP_PORT}}}" # Tell caddy to reverse proxy the JELLYFIN_HTTP_PORT
    networks:
      - external # Listen on the "external" network created in root/compose.yml
    ports:
      - 7359:7359/udp # Autodiscovery
    volumes:
      - ${MEDIALIBRARY_PATH}:/data # Media library path
      - jellyfin:/config # Configuration path
