services:
    picard:
        container_name: "picard"
        image: "mikenye/picard:latest"
        hostname: "picard"
        restart: "no" # Do not automatically restart Picard; run as-needed.
        security_opt: ["no-new-privileges:true"]
        environment:
            GROUP_ID: ${PGID} # Group ID to run the container as.
            TZ: ${TZ} # Timezone to configure the container to use.
            UMASK: ${UMASK} # Default umask permissions to apply to newly created files.
            USER_ID: ${PUID} # User ID to run the container as.
        networks:
            - "frontend" # Local frontend network.
        ports:
            - "${PICARD_PORT:-5800}:5800/tcp" # Local web interface.
        volumes:
            - "music-library:/storage" # Music library.
            - "picard:/config" # Configuration and data volume.

networks:
    frontend:
        driver: "bridge"
        external: "true"
        name: "frontend-network"

volumes:
    music-library:
        name: "music-library-volume"
        driver_opts:
            device: "${MEDIA_LIBRARY_PATH}/music"
            o: "bind"
            type: "none"
    picard:
        external: "true"
        name: "picard-volume"
