services:
    picard:
        container_name: picard
        image: mikenye/picard:2.13.3
        restart: no # Do not automatically restart Picard; run as-needed.
        environment:
            GROUP_ID: ${PGID}
            TZ: ${TZ}
            UMASK: ${UMASK}
            USER_ID: ${PUID}
        networks:
            - frontend
        ports:
            - ${PICARD_PORT:-5800}:5800/tcp # Picard web interface.
        volumes:
            - music:/storage # Music library.
            - picard:/config # Configuration and data volume.
        security_opt:
            - no-new-privileges:true

volumes:
    music:
        name: music-volume
        driver_opts:
            device: ${MEDIA_LIBRARY_PATH}/music
            o: bind
            type: none
    picard:
        external: true
        name: picard-volume
