services:
  radarr:
    container_name: radarr
    image: ghcr.io/11notes/radarr:5
    env_file: ../../.env
    hostname: radarr
    read_only: true
    restart: unless-stopped
    environment:
      - TZ=${TZ} # Timezone to run the container under.
    networks:
      - gluetun
      - internal
    ports:
      - ${RADARR_WEBUI_PORT:-7878}:7878/tcp # Local Radarr web interface.
    volumes:
      - ${DOWNLOADS_DIRECTORY}:/downloads # Root downloads path; needs to be writable by 1000:1000.
      - ${MEDIA_LIBRARY_DIRECTORY}:/library # Root media library path; needs to be writable by 1000:1000.
      - radarr:/radarr/etc # Radarr configuration/data volume.
    depends_on:
      qbittorrent:
        condition: service_healthy # Wait for qBittorrent to become healthy before starting.
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=1000,gid=1000 # Required for read-only images.
