---
services:
    ###############################################################################
    # Cloudflare-DDNS: Dynamically update Cloudflare DNS records.                 #
    ##############################################################################

    cloudflare-ddns:
        image: favonia/cloudflare-ddns:1
        container_name: cloudflare-ddns
        network_mode: host # Makes getting IP more consistent.
        read_only: true
        restart: unless-stopped
        user: ${PUID}:${PGID}
        cap_drop:
            - ALL # Remove all permissions.
        environment:
            CLOUDFLARE_API_TOKEN: "${CLOUDFLARE_API_TOKEN}" # Scoped Cloudflare account token with DNS Zone edit permissions.
            IP4_DOMAINS: "${CLOUDFLARE_DOMAINS}" # List of domains to update DNS records for.
            EMOJI: "false" # Disable emoji inside of log files.
            IP6_PROVIDER: "none" # Disable IPV6.
            PROXIED: "false" # Disable proxying service traffic through Cloudflare.
            TZ: "${TZ}" # Local timezone to use.
            UPDATE_CRON: "@every 1h" # Checks for an updated IP address every hour.
