services:
  cloudflare-ddns:
    container_name: cloudflare-ddns
    image: favonia/cloudflare-ddns:latest
    cap_drop: [ALL]
    env_file: ../../.env
    network_mode: host # cloudflare-ddns requires network_mode: host to get the origin IP.
    read_only: true
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN} # A scoped Cloudflare account token with DNS Zone edit permissions.
      - EMOJI=false # Emojis do not belong in the CLI, what is wrong with you?
      - IP4_DOMAINS=${CLOUDFLARE_DOMAINS} # List of domains to add records for.
      - IP6_PROVIDER=none # Disable IPV6 support (for now)
      - PROXIED=true # Enable proxying content through Cloudflare - be sure to make a rule to not cache Jellyfin content!
      - TZ=${TZ}
      - UPDATE_CRON=@every 8h # Checks for an updated IP address every 8 hours.
    healthcheck:
      interval: 5m
      retries: 3
      start_period: 1m
      test: ["CMD", "pgrep", "-x", "ddns"] # Check if the DDNS command is running.
      timeout: 10s
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
