services:
  cloudflare-ddns:
    container_name: cloudflare-ddns
    image: favonia/cloudflare-ddns:1.15.1
    env_file: ../../.env
    network_mode: host # Required to get the origin IP.
    read_only: true
    restart: unless-stopped
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN} # A scoped Cloudflare account token with DNS Zone edit permissions.
      - EMOJI=false
      - QUIET=true # Adjust the logging priority.
      - IP4_DOMAINS=${CLOUDFLARE_DOMAINS} # List of domains to add A records for.
      - IP6_PROVIDER=none # Disable IPV6 support (for now).
      - PROXIED=true # Enable proxying service traffic through Cloudflare.
      - TZ=${TZ}
      - UPDATE_CRON=@every 24h # Checks for an updated IP address every 24 hours.
    cap_drop:
      - ALL
    healthcheck:
      interval: 5m
      retries: 3
      start_period: 1m
      test: ["CMD", "pgrep", "-x", "ddns"] # Check if the DDNS command is running.
      timeout: 10s
    security_opt:
      - no-new-privileges:true
