services:
  lidarr:
    container_name: lidarr
    image: blampe/lidarr:latest
    env_file: ../../.env
    hostname: lidarr
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    networks:
      - frontend # Internal network for local web interface access.
      - gluetun # Gluetun VPN network.
      - media # Internal media network.
    ports:
      - ${LIDARR_WEBUI_PORT:-8989}:8989 # Lidarr WebUI.
    volumes:
      - ${DOWNLOADS_DIRECTORY}:/downloads
      - ${MEDIA_LIBRARY_DIRECTORY}:/library
      - lidarr:/config
    depends_on:
      qbittorrent:
        condition: service_healthy # Wait for download clients to become healthy before starting.
    healthcheck:
      interval: 5m
      retries: 3
      start_period: 2m
      test: ["CMD", "curl", "-f", "http://localhost:8686/ping"]
      timeout: 10s
    security_opt:
      - no-new-privileges:true

networks:
  frontend:
    name: frontend-network
    driver: bridge
    enable_ipv6: false
    external: true
  gluetun:
    name: gluetun-network
    driver: bridge
    enable_ipv6: false
    external: true
  media:
    name: media-network
    driver: bridge
    enable_ipv6: false
    external: true

volumes:
  lidarr:
    name: lidarr-volume
    external: true
