services:
  lidarr:
    container_name: lidarr
    image: blampe/lidarr:latest
    depends_on:
      gluetun:
        condition: service_healthy
    env_file:
      - ../../.env
    network_mode: service:gluetun
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    healthcheck:
      interval: 5m
      retries: 3
      start_period: 2m
      test: ["CMD", "curl", "-f", "http://localhost:8686/ping"]
      timeout: 10s
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - ${DOWNLOADS_DIRECTORY}:/downloads
      - ${MEDIA_LIBRARY_DIRECTORY}:/library
      - lidarr:/config
