services:
  nextcloud:
    container_name: nextcloud
    image: lscr.io/linuxserver/nextcloud:latest
    cap_drop: [ALL]
    env_file: ../../.env
    read_only: true
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    depends_on:
      nextcloud-mariadb:
        condition: service_healthy
      nextcloud-valkey:
        condition: service_healthy
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - SETGID
      - SETUID
      - SYS_NICE
    environment:
      - LOGLEVEL=1
      - MYSQL_DATABASE=${NEXTCLOUD_MARIADB_DATABASE}
      - MYSQL_HOST=nextcloud-mariadb
      - MYSQL_PASSWORD=${NEXTCLOUD_MARIADB_PASSWORD}
      - MYSQL_USER=${NEXTCLOUD_MARIADB_USER}
      - NC_default_phone_region=US
      - NC_skeletondirectory=
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_HOSTNAME=${URL_PUBLISHED_NEXTCLOUD}
      - NEXTCLOUD_INIT_HTACCESS=true
      - NEXTCLOUD_TRUSTED_DOMAINS=${URL_PUBLISHED_NEXTCLOUD}
      - OVERWRITECLIURL=https://${URL_PUBLISHED_NEXTCLOUD}
      - OVERWRITEHOST=${URL_PUBLISHED_NEXTCLOUD}
      - OVERWRITEPROTOCOL=https
      - PGID=${PGID}
      - PHP_MEMORY_LIMIT=8G
      - PHP_UPLOAD_LIMIT=8G
      - PUID=${PUID}
      - REDIS_HOST=nextcloud-valkey
      - SMTP_HOST=${NEXTCLOUD_SMTP_HOST}
      - SMTP_NAME=${NEXTCLOUD_SMTP_NAME}
      - SMTP_PASSWORD=${NEXTCLOUD_SMTP_PASSWORD}
      - SMTP_SECURE=ssl
      - TRUSTED_PROXIES=172.19.0.0/16
      - TZ=${TZ}
      - UMASK=022
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 120s
      test: ["CMD", "curl", "-f", "http://localhost/index.php"]
      timeout: 10s
    labels:
      caddy: ${URL_PUBLISHED_NEXTCLOUD}
      caddy.header: Strict-Transport-Security "max-age=15552000; includeSubDomains"
      caddy.reverse_proxy: nextcloud:443
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      - external
      - nextcloud-internal
    volumes:
      - ${PATH_NEXTCLOUD_DATA}:/data
      - nextcloud:/config
      - type: tmpfs # Map /tmp for tmpfs usage.
        target: /tmp
        tmpfs:
          size: 1000000000 # Limit to 1GB.

  nextcloud-mariadb:
    container_name: nextcloud-mariadb
    image: lscr.io/linuxserver/mariadb:latest
    cap_drop: [ALL]
    env_file: ../../.env
    networks: [nextcloud-internal]
    read_only: true
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - SETGID
      - SETUID
    environment:
      - MYSQL_DATABASE=${NEXTCLOUD_MARIADB_DATABASE}
      - MYSQL_PASSWORD=${NEXTCLOUD_MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MARIADB_ROOT_PASSWORD}
      - MYSQL_USER=${NEXTCLOUD_MARIADB_USER}
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 30s
      test:
        - CMD
        - mariadb-admin
        - ping
        - -h
        - "localhost"
        - "-u${NEXTCLOUD_MARIADB_USER}"
        - "-p${NEXTCLOUD_MARIADB_PASSWORD}"
      timeout: 10s
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    volumes:
      - nextcloud-mariadb:/config
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 100M

  nextcloud-valkey:
    container_name: nextcloud-valkey
    image: ghcr.io/valkey-io/valkey:latest
    cap_drop: [ALL]
    env_file: ../../.env
    networks: [nextcloud-internal]
    read_only: true
    restart: unless-stopped
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - SETGID
      - SETUID
    environment:
      - PASSWORD=${NEXTCLOUD_VALKEY_PASSWORD}
    healthcheck:
      interval: 30s
      retries: 3
      test: ["CMD", "redis-cli", "-a", "${NEXTCLOUD_VALKEY_PASSWORD}", "ping"]
      timeout: 10s
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    volumes:
      - nextcloud-valkey:/data
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 64M
