services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud:apache
    restart: unless-stopped
    depends_on:
      nextcloud-mariadb:
        condition: service_healthy
      nextcloud-redis:
        condition: service_healthy
    env_file:
      - ../../.env
    environment:
      - LOGLEVEL=1
      - MAIL_DOMAIN=${MAIL_DOMAIN}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MYSQL_DATABASE=${NEXTCLOUD_MYSQL_DATABASE}
      - MYSQL_HOST=nextcloud-mariadb
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
      - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}
      - NC_default_phone_region="US"
      - NC_skeletondirectory=
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_HOSTNAME=${URL_PUBLISHED_NEXTCLOUD}
      - NEXTCLOUD_INIT_HTACCESS=true
      - NEXTCLOUD_TRUSTED_DOMAINS=${URL_PUBLISHED_NEXTCLOUD}
      - OVERWRITECLIURL=https://${URL_PUBLISHED_NEXTCLOUD}
      - OVERWRITEHOST=${URL_PUBLISHED_NEXTCLOUD}
      - OVERWRITEPROTOCOL=https
      - PGID=${PGID}
      - PHP_MEMORY_LIMIT=8G
      - PHP_UPLOAD_LIMIT=8G
      - PUID=${PUID}
      - REDIS_HOST=nextcloud-redis
      - SMTP_HOST=${MAIL_SMTP_HOST}
      - SMTP_NAME=${MAIL_SMTP_NAME}
      - SMTP_PASSWORD=${MAIL_SMTP_PASSWORD}
      - SMTP_SECURE=ssl
      - TRUSTED_PROXIES=172.19.0.0/16
      - UMASK=022
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 120s
      test: ["CMD", "curl", "-f", "http://localhost/status.php"]
      timeout: 10s
    labels:
      caddy: ${URL_PUBLISHED_NEXTCLOUD}
      caddy.header: Strict-Transport-Security "max-age=15552000; includeSubDomains"
      caddy.reverse_proxy: nextcloud:80
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      - external
      - nextcloud-internal
    volumes:
      - ${PATH_NEXTCLOUD_DATA}:/var/www/html/data
      - nextcloud:/var/www/html
      - target: /tmp
        tmpfs:
          size: 1000000000
        type: tmpfs

  nextcloud-mariadb:
    container_name: nextcloud-mariadb
    image: mariadb:latest
    restart: unless-stopped
    env_file:
      - ../../.env
    environment:
      - MYSQL_DATABASE=${NEXTCLOUD_MYSQL_DATABASE}
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 30s
      test:
        - CMD
        - mariadb-admin
        - ping
        - "-h"
        - localhost
        - "-u${NEXTCLOUD_MYSQL_USER}"
        - "-p${NEXTCLOUD_MYSQL_PASSWORD}"
      timeout: 10s
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      - nextcloud-internal
    security_opt:
      - no-new-privileges:true
    volumes:
      - nextcloud-mariadb:/var/lib/mysql

  nextcloud-redis:
    container_name: nextcloud-redis
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      interval: 30s
      retries: 3
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      - nextcloud-internal
    volumes:
      - nextcloud-redis:/data
