services:
  nextcloud:
    container_name: nextcloud
    image: lscr.io/linuxserver/nextcloud:latest
    cap_drop: [ALL]
    env_file: ../../.env
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    cap_add:
      - NET_BIND_SERVICE # Port binding.
      - SYS_NICE # PHP process scheduling.
    depends_on:
      nextcloud-mariadb:
        condition: service_healthy
      nextcloud-valkey:
        condition: service_healthy
    environment:
      - MYSQL_DATABASE=${NEXTCLOUD_MARIADB_DATABASE}
      - MYSQL_HOST=nextcloud-mariadb
      - MYSQL_PASSWORD=${NEXTCLOUD_MARIADB_PASSWORD}
      - MYSQL_USER=${NEXTCLOUD_MARIADB_USER}
      - NC_default_phone_region=US # Set US as default_phone_region.
      - NC_skeletondirectory= # Disable skeleton directory.
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - PHP_MEMORY_LIMIT=8G # PHP memory limit.
      - PHP_UPLOAD_LIMIT=8G # PHP upload limit.
      - REDIS_HOST=nextcloud-valkey
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 120s
      test: ["CMD", "curl", "-f", "http://localhost/index.php"]
      timeout: 10s
    labels:
      caddy: ${URL_PUBLISHED_NEXTCLOUD} # Tell Caddy to reverse proxy to our URL_PUBLISHED_NEXTCLOUD.
      caddy.header: Strict-Transport-Security "max-age=15552000; includeSubDomains" # HSTS.
      caddy.reverse_proxy: nextcloud:443
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 10m
    networks:
      - external
      - nextcloud-internal
    volumes:
      - ${PATH_NEXTCLOUD_DATA}:/data # Nextcloud data path.
      - nextcloud:/config
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 1000000000 # Limit to 1GB.

  # Nextcloud MariaDB database
  nextcloud-mariadb:
    container_name: nextcloud-mariadb
    image: lscr.io/linuxserver/mariadb:latest
    cap_add: [NET_BIND_SERVICE] # Port binding.
    cap_drop: [ALL]
    env_file: ../../.env
    networks: [nextcloud-internal]
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${NEXTCLOUD_MARIADB_DATABASE}
      - MYSQL_USER=${NEXTCLOUD_MARIADB_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_MARIADB_PASSWORD}
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 30s
      test:
        - CMD
        - mariadb-admin
        - ping
        - -h
        - "localhost"
        - "-u${NEXTCLOUD_MARIADB_USER}"
        - "-p${NEXTCLOUD_MARIADB_PASSWORD}"
      timeout: 10s
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    volumes:
      - nextcloud-mariadb:/config
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 100000000 # 100MB

  # Nextcloud Valkey/Redis cache
  nextcloud-valkey:
    container_name: nextcloud-valkey
    image: ghcr.io/valkey-io/valkey:latest
    cap_add: [NET_BIND_SERVICE] # Port binding.
    cap_drop: [ALL]
    env_file: ../../.env
    networks: [nextcloud-internal]
    restart: unless-stopped
    environment:
      - PASSWORD=${NEXTCLOUD_VALKEY_PASSWORD}
    healthcheck:
      interval: 30s
      retries: 3
      test: ["CMD", "redis-cli", "-a", "${NEXTCLOUD_VALKEY_PASSWORD}", "ping"]
      timeout: 10s
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    volumes:
      - nextcloud-valkey:/data # Valkey data; created in root/compose.yml.
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 100000000 # 100MB
