services:
    syncthing:
        container_name: syncthing
        image: ghcr.io/11notes/syncthing:2
        read_only: true
        restart: unless-stopped
        environment:
            SYNCTHING_API_KEY: ${SYNCTHING_API_KEY} # 32-character API key to use.
            SYNCTHING_PASSWORD: ${SYNCTHING_PASSWORD} # 32-character administrator password to use.
            TZ: ${TZ}
        networks:
            - frontend
            - internal
        ports:
            - ${SYNCTHING_PORT}:3000/tcp # Syncthing web interface.
            - ${SYNCTHING_TRAFFIC_PORT:-22000}:22000/tcp # Syncthing traffic, TCP.
            - ${SYNCTHING_TRAFFIC_PORT:-22000}:22000/udp # Syncthing traffic, UDP.
            - ${SYNCTHING_AUTODISCOVERY_PORT:-21027}:21027/udp # Syncthing autodiscovery.
        volumes:
            - syncthing-etc:/syncthing/etc # Configuration volume.
            - syncthing-share:/syncthing/share # Stored data volume.
            - syncthing-var:/syncthing/var # Database and index volume.
        security_opt:
            - no-new-privileges:true

volumes:
    syncthing-etc:
        name: syncthing-etc-volume
        driver_opts:
            device: ${SYNCTHING_DATA_PATH}/etc
            o: bind
            type: none
    syncthing-var:
        name: syncthing-var-volume
        driver_opts:
            device: ${SYNCTHING_DATA_PATH}/var
            o: bind
            type: none
    syncthing-share:
        name: syncthing-share-volume
        driver_opts:
            device: ${SYNCTHING_DATA_PATH}/share
            o: bind
            type: none
