services:
    unpackerr:
        container_name: unpackerr
        image: ghcr.io/unpackerr/unpackerr:0.14.5
        restart: unless-stopped
        user: ${PUID}:${PGID}
        environment:
            TZ: ${TZ}
            UN_LOG_FILE: /downloads/unpackerr.log # Log file location.
            UN_RADARR_0_API_KEY: ${RADARR_API_KEY} # Radarr API key.
            UN_RADARR_0_URL: http://localhost:7878 # Primary Radarr URL.
            UN_SONARR_0_API_KEY: ${SONARR_API_KEY} # Sonarr API key.
            UN_SONARR_0_URL: http://localhost:8989 # Primary Sonarr URL.
        network_mode: service:gluetun # Route all networking through Gluetun.
        volumes:
            - downloads:/downloads # Downloads directory.
        depends_on:
            gluetun:
                condition: service_healthy # Require Gluetun to be healthy before connecting.
                restart: true

        security_opt:
            - no-new-privileges:true
