services:
    unpackerr:
        container_name: "unpackerr"
        image: "ghcr.io/unpackerr/unpackerr:latest"
        hostname: "unpackerr"
        restart: "unless-stopped"
        security_opt: ["no-new-privileges:true"]
        user: "${PUID}:${PGID}"
        environment:
            TZ: "${TZ}" # Timezone to configure the container to use.
            UN_LOG_FILE: "/downloads/unpackerr.log" # Log file location.
            UN_RADARR_0_API_KEY: "${RADARR_API_KEY}" # Radarr API key.
            UN_RADARR_0_URL: "http://radarr:7878" # Primary Radarr URL.
            UN_SONARR_0_API_KEY: "${SONARR_API_KEY}" # Sonarr API key.
            UN_SONARR_0_URL: "http://sonarr:8989" # Primary Sonarr URL.
        networks:
            - "media"
        volumes:
            - "downloads:/downloads" # Root downloads directory volume.

networks:
    media:
        driver: "bridge"
        external: "true"
        name: "media-network"

volumes:
    downloads:
        name: "downloads-volume"
        driver_opts:
            device: "${DOWNLOADS_PATH}" # Root downloads directory path.
            o: "bind"
            type: "none"
