---
services:
    ###############################################################################
    # Unpackerr: Automatic extraction of downloaded files.                        #
    ##############################################################################

    unpackerr:
        image: ghcr.io/unpackerr/unpackerr:0
        container_name: unpackerr
        hostname: unpackerr
        restart: unless-stopped
        user: ${PUID}:${PGID}
        environment:
            TZ: "${TZ}" # Configures the timezone to use.
            PGID: "${PGID}" # Local group to run as.
            PUID: "${PUID}" # Local user to run as.
            UN_LOG_FILE: "/downloads/unpackerr.log" # Log file location.
            UN_RADARR_0_API_KEY: "${RADARR_API_KEY}" # Radarr API key.
            UN_RADARR_0_URL: "http://radarr:7878" # Primary Radarr URL.
            UN_SONARR_0_API_KEY: "${SONARR_API_KEY}" # Sonarr API key.
            UN_SONARR_0_URL: "http://sonarr:8989" # Primary Sonarr URL.
        networks:
            - gluetun
        volumes:
            - downloads:/downloads
networks:
    gluetun:
        driver: bridge
        enable_ipv6: false
        external: true
        name: gluetun-network # $ docker network create --ipv6=false gluetun-network

volumes:
    downloads:
        name: downloads-volume
        driver_opts:
            device: "${DOWNLOADS_PATH}" # Root path to store downloaded files into.
            o: bind
            type: none
