services:
    unpackerr:
        container_name: "unpackerr"
        image: "ghcr.io/unpackerr/unpackerr:0"
        restart: "unless-stopped"
        security_opt: ["no-new-privileges:true"] # Prevents privilege escalation.
        user: ${PUID}:${PGID} # The user to run the container under.
        environment:
            TZ: "${TZ}" # Timezone to run the container under.
            UN_LOG_FILE: "/downloads/unpackerr.log" # Log file location.
            UN_RADARR_0_API_KEY: "${RADARR_API_KEY}" # Radarr API key.
            UN_RADARR_0_URL: "http://radarr:7878" # Primary Radarr URL.
            UN_SONARR_0_API_KEY: "${SONARR_API_KEY}" # Sonarr API key.
            UN_SONARR_0_URL: "http://sonarr:8989" # Primary Sonarr URL.
        volumes:
            - "downloads:/downloads" # Downloads directory.
