services:
    profilarr:
        container_name: profilarr
        image: santiagosayshey/profilarr:v1.1.3
        restart: unless-stopped
        environment:
            TZ: ${TZ}
        networks:
            - media
        ports:
            - ${PROFILARR_PORT:-6868}:6868/tcp # Profilarr web interface.
        volumes:
            - profilarr:/config # Configuration and data volume.
        depends_on:
            radarr:
                condition: service_healthy # Require Radarr to be healthy before connecting.
                restart: true
            sonarr:
                condition: service_healthy # Require Sonarr to be healthy before connecting.
                restart: true
        security_opt:
            - no-new-privileges:true

volumes:
    profilarr:
        external: true
        name: profilarr-volume
