services:
    profilarr:
        container_name: profilarr
        image: santiagosayshey/profilarr:v1.1.3
        restart: unless-stopped
        environment:
            TZ: ${TZ}
        network_mode: service:gluetun # Route all networking through Gluetun.
        volumes:
            - profilarr:/config # Configuration and data volume.
        depends_on:
            gluetun:
                condition: service_healthy # Require Gluetun to be healthy before connecting.
                restart: true
            radarr:
                condition: service_healthy # Require Radarr to be healthy before connecting.
                restart: true
            sonarr:
                condition: service_healthy # Require Sonarr to be healthy before connecting.
                restart: true
        security_opt:
            - no-new-privileges:true

volumes:
    profilarr:
        external: true
        name: profilarr-volume
