services:
    profilarr:
        container_name: "profilarr"
        image: "santiagosayshey/profilarr:v1.1.3"
        restart: "unless-stopped"
        security_opt: ["no-new-privileges:true"] # Prevents privilege escalation.
        depends_on:
            radarr:
                condition: "service_healthy" # Require Radarr to be healthy before connecting.
                restart: true
            sonarr:
                condition: "service_healthy" # Require Sonarr to be healthy before connecting.
                restart: true
        environment:
            TZ: "${TZ}" # Timezone to run the container under.
        healthcheck:
            interval: "1m"
            retries: "3"
            start_period: "15s"
            test: ["CMD", "curl", "-f", "http://localhost:6868"]
            timeout: "3s"
        networks:
            - "media" # Internal media network.
        ports:
            - "${PROFILARR_PORT:-6868}:6868/tcp" # Profilarr web interface.
        volumes:
            - "profilarr:/config" # Configuration and data volume.

volumes:
    profilarr:
        external: true
        name: "profilarr-volume"
