services:
    profilarr:
        container_name: "profilarr"
        image: "santiagosayshey/profilarr:latest"
        restart: "unless-stopped"
        security_opt: ["no-new-privileges:true"]
        environment:
            TZ: "${TZ}" # Timezone to configure the container to use.
        networks:
            - "frontend" # Local frontend network.
            - "media" # Media stack network.
        ports:
            - "${PROFILARR_PORT:-6868}:6868/tcp" # Local web interface.
        volumes:
            - "profilarr:/config" # Configuration and data volume.

volumes:
    profilarr:
        external: "true"
        name: "profilarr-volume"

networks:
    frontend:
        driver: "bridge"
        external: "true"
        name: "frontend-network"
    media:
        driver: "bridge"
        external: "true"
        name: "media-network"
