---
services:
    ###############################################################################
    # Gluetun: VPN client. I use AirVPN.                                          #
    ###############################################################################

    gluetun:
        image: ghcr.io/qdm12/gluetun:v3
        container_name: gluetun
        hostname: gluetun
        restart: unless-stopped
        devices:
            - /dev/net/tun:/dev/net/tun # TUN/TAP device passthrough.
        environment:
            BLOCK_MALICIOUS: "off" # https://github.com/qdm12/gluetun/issues/765
            FIREWALL_OUTBOUND_SUBNETS: "${FIREWALL_OUTBOUND_SUBNETS}" # Allow the Docker network to access the Gluetun network.
            FIREWALL_VPN_INPUT_PORTS: "${FIREWALL_VPN_INPUT_PORTS}" # Ports allowed to be forwarded by the VPN provider.
            PGID: "${PGID}" # Local group to run as.
            PUID: "${PUID}" # Local user to run as.
            SERVER_CITIES: "${SERVER_CITIES}" # Server cities to connect to.
            SERVER_COUNTRIES: "${SERVER_COUNTRIES}" # Server countries to connect to.
            SERVER_HOSTNAMES: "${SERVER_HOSTNAMES}" # Server hostnames to connect to.
            SERVER_NAMES: "${SERVER_NAMES}" # Server names to connect to.
            SERVER_REGIONS: "${SERVER_REGIONS}" # Server regions to connect to.
            TZ: "${TZ}" # Configures the timezone to use.
            UPDATER_PERIOD: "24h" # Update server data every 24 hours.
            VPN_SERVICE_PROVIDER: "${VPN_SERVICE_PROVIDER}" # https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers.
            VPN_TYPE: "wireguard" # Use Wireguard for VPN connections.
            WIREGUARD_ADDRESSES: "${WIREGUARD_ADDRESSES}" # Addresses from wg0.conf.
            WIREGUARD_ENDPOINT_PORT: "${WIREGUARD_ENDPOINT_PORT}" # Endpoint port from wg0.conf.
            WIREGUARD_MTU: "1380" # https://github.com/qdm12/gluetun-wiki/issues/140
            WIREGUARD_PRESHARED_KEY: "${WIREGUARD_PRESHARED_KEY}" # PresharedKey from wg0.conf.
            WIREGUARD_PRIVATE_KEY: "${WIREGUARD_PRIVATE_KEY}" # PrivateKey from wg0.conf.
            WIREGUARD_PUBLIC_KEY: "${WIREGUARD_PUBLIC_KEY}" # PublicKey from wg0.conf.
        expose:
            - 5030/tcp # slskd http server.
            - 50300/tcp # Soulseek traffic.
            - 8080/tcp # qBittorrent web interface.
            - 8191/tcp # Flaresolverr server.
            - 9696/tcp # Prowlarr web interface.
        networks:
            - caddy
            - gluetun
        volumes:
            - gluetun:/gluetun
        cap_add:
            - NET_ADMIN # Required for Wireguard configuration.
        security_opt:
            - no-new-privileges:true

    ###############################################################################
    # qBittorrent: BitTorrent client.                                             #
    ###############################################################################

    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        network_mode: service:gluetun # Route all traffic through Gluetun.
        restart: unless-stopped
        environment:
            DOCKER_MODS: "ghcr.io/gabe565/linuxserver-mod-vuetorrent" # Auto-install Vuetorrent to /vuetorrent.
            PGID: "${PGID}" # Local group to run as.
            PUID: "${PUID}" # Local user to run as.
            TZ: "${TZ}" # Configures the timezone to use.
            UMASK: "${UMASK}" # Default umask to apply to newly created files.
        healthcheck:
            interval: 1m
            start_period: 30s
            test: "ifconfig | grep -q eth0"
        volumes:
            - downloads:/downloads
            - qbittorrent:/config
        depends_on:
            gluetun:
                condition: service_healthy
                restart: true
        security_opt:
            - no-new-privileges:true

    ###############################################################################
    # Prowlarr: Indexer manager for 'ARR apps.                                    #
    ###############################################################################

    prowlarr:
        image: ghcr.io/hotio/prowlarr:release
        container_name: prowlarr
        network_mode: service:gluetun # Route all traffic through Gluetun.
        restart: unless-stopped
        environment:
            PGID: "${PGID}" # Local group to run as.
            PUID: "${PUID}" # Local user to run as.
            TZ: "${TZ}" # Configures the timezone to use.
            UMASK: "${UMASK}" # Default umask to apply to newly created files.
        volumes:
            - downloads:/downloads
            - prowlarr:/prowlarr/etc
        depends_on:
            gluetun:
                condition: service_healthy
                restart: true
        security_opt:
            - no-new-privileges:true

    ###############################################################################
    # Flaresolverr: DDoS-Guard and Cloudflare captcha solver.                     #
    ###############################################################################

    flaresolverr:
        image: ghcr.io/flaresolverr/flaresolverr:v3.4.1
        container_name: flaresolverr
        network_mode: service:gluetun # Route all traffic through Gluetun.
        restart: unless-stopped
        user: ${PUID}:${PGID}
        environment:
            TZ: "${TZ}" # Configures the timezone to use.
        depends_on:
            gluetun:
                condition: service_healthy
                restart: true
        cap_drop:
            - ALL
        security_opt:
            - no-new-privileges:true

    ###############################################################################
    # Unpackerr: Automatic extraction of downloaded files.                        #
    ###############################################################################

    unpackerr:
        image: ghcr.io/unpackerr/unpackerr:0.14.5
        container_name: unpackerr
        hostname: unpackerr
        restart: unless-stopped
        user: ${PUID}:${PGID}
        environment:
            TZ: "${TZ}" # Configures the timezone to use.
            UN_LOG_FILE: "/downloads/unpackerr.log" # Log file location.
            UN_RADARR_0_API_KEY: "${RADARR_API_KEY}" # Radarr API key.
            UN_RADARR_0_URL: "http://radarr:7878" # Primary Radarr URL.
            UN_SONARR_0_API_KEY: "${SONARR_API_KEY}" # Sonarr API key.
            UN_SONARR_0_URL: "http://sonarr:8989" # Primary Sonarr URL.
        networks:
            - gluetun
        volumes:
            - downloads:/downloads

    ###############################################################################
    # Deemix: Deezer downloads client.                                            #
    ###############################################################################

    deemix:
        image: ghcr.io/bambanah/deemix:v4.3.5
        container_name: deemix
        restart: unless-stopped
        hostname: deemix
        environment:
            DEEMIX_SINGLE_USER: "true" # Use one global user.
            TZ: "${TZ}" # Configures the timezone to use.
            UMASK_SET: "${UMASK}" # Umask to apply to newly created files.
        networks:
            - caddy
            - gluetun
        expose:
            - 6595/tcp
        volumes:
            - deemix-downloads:/downloads
            - deemix:/config
        security_opt:
            - no-new-privileges:true

    ###############################################################################
    # slskd: Web-based Soulseek client.                                           #
    ###############################################################################

    slskd:
        image: ghcr.io/slskd/slskd:0.23.2
        container_name: slskd
        network_mode: service:gluetun # Route all traffic thru Gluetun.
        restart: unless-stopped
        user: ${PUID}:${PGID}
        environment:
            TZ: "${TZ}" # Configures the timezone to use.
            SLSKD_REMOTE_CONFIGURATION: "true" # Allows configuring settings through the web interface.
            SLSKD_UMASK: "${UMASK}" # Configures the umask to set on newly created files.
        volumes:
            - slskd:/app
            - soulseek-downloads:/downloads
        depends_on:
            gluetun:
                condition: service_healthy
                restart: true
        security_opt:
            - no-new-privileges:true

    ###############################################################################
    # Soularr: Soulseek integration for lidarr.                                   #
    ###############################################################################

    soularr:
        image: ghcr.io/mrusse/soularr:main
        container_name: soularr
        network_mode: service:gluetun
        restart: unless-stopped
        user: ${PUID}:${PGID}
        environment:
            TZ: "${TZ}" # Configures the timezone to use.
        volumes:
            - soularr:/data
            - soulseek-downloads:/downloads
        depends_on:
            gluetun:
                condition: service_healthy
                restart: true
            lidarr:
                condition: service_started
                restart: true
            slskd:
                condition: service_healthy
                restart: true
        security_opt:
            - no-new-privileges:true

    ###############################################################################
    # mam-ip-helper: Update MyAnonaMouse seedbox session to match Gluetun's IP.   #
    ###############################################################################

    mam-ip-helper:
        image: tyzen9/myanonamouse-ip-helper:1.0.0
        container_name: mam-ip-helper
        network_mode: service:gluetun # Route all traffic through Gluetun.
        read_only: true
        restart: unless-stopped
        user: ${PUID}:${PGID}
        environment:
            TZ: "${TZ}" # Configures the timezone to use.
            MAM_ID: "${MAM_ID}" # MyAnonaMouse session ID.
        cap_drop:
            - ALL
        depends_on:
            gluetun:
                condition: service_healthy
                restart: true
        security_opt:
            - no-new-privileges:true

networks:
    caddy:
        external: true
        name: caddy-network # $ docker network create caddy-network
    gluetun:
        external: true
        name: gluetun-network # $ docker network create gluetun-network

volumes:
    deemix:
        external: true
        name: deemix-volume # $ docker volume create deemix-volume
    qbittorrent:
        external: true
        name: qbittorrent-volume # $ docker volume create qbittorrent-volume
    gluetun:
        external: true
        name: gluetun-volume # $ docker volume create gluetun-volume
    prowlarr:
        external: true
        name: prowlarr-volume # $ docker volume create prowlarr-volume
    slskd:
        external: true
        name: slskd-volume # $ docker volume create slskd-volume
    soularr:
        external: true
        name: soularr-volume
    deemix-downloads:
        name: deemix-downloads-volume
        driver_opts:
            device: "${DOWNLOADS_PATH}/deemix" # Root path to store downloaded deemix files into.
            o: bind
            type: none
    soulseek-downloads:
        name: soulseek-downloads-volume
        driver_opts:
            device: "${DOWNLOADS_PATH}/soulseek" # Root path to store downloaded soulseek files into.
            o: bind
            type: none
    downloads:
        name: downloads-volume
        driver_opts:
            device: "${DOWNLOADS_PATH}" # Root path to store downloaded files into.
            o: bind
            type: none
