services:
    deemix:
        container_name: deemix
        image: ghcr.io/bambanah/deemix:v4.3.5
        restart: unless-stopped
        environment:
            DEEMIX_SINGLE_USER: true # Use one global user.
            PGID: ${PGID}
            PUID: ${PUID}
            TZ: ${TZ}
            UMASK_SET: ${UMASK}
        network_mode: service:gluetun # Route all networking through Gluetun.
        volumes:
            - deemix:/config # Configuration and data volume.
            - deemix-downloads:/downloads # Root Deemix downloads volume.
        depends_on:
            gluetun:
                condition: service_healthy # Require Gluetun to be healthy before connecting.
                restart: true
        healthcheck:
            interval: 1m
            retries: 3
            start_period: 15s
            test: ["CMD", "curl", "-f", "http://localhost:6595/"]
            timeout: 3s
        security_opt:
            - no-new-privileges:true

volumes:
    deemix:
        external: true
        name: deemix-volume
    deemix-downloads:
        name: deemix-downloads-volume
        driver_opts:
            device: ${DOWNLOADS_PATH}/deemix
            o: bind
            type: none
