---
services:
    ###############################################################################
    # Deemix: Music download client for Deezer.                                  #
    ##############################################################################

    deemix:
        image: ghcr.io/bambanah/deemix:v4.3.5
        container_name: deemix
        hostname: deemix
        restart: unless-stopped
        environment:
            DEEMIX_SINGLE_USER: "true" # Use one global user.
            TZ: "${TZ}" # Configures the timezone to use.
            PGID: "${PGID}" # Local group to run as.
            PUID: "${PUID}" # Local user to run as.
            UMASK_SET: "${UMASK}" # Umask to apply to newly created files.
        healthcheck:
            interval: 1m
            test: "curl -f http://127.0.0.1:6595 || exit 1"
        labels:
            caddy: "deemix.${INTERNAL_DOMAIN}" # Reverse proxy to the internal domain.
            caddy.import: "internal deemix:6595" # Reverse proxy internal traffic.
            caddy.tls.ca: "https://acme.zerossl.com/v2/DV90" # Use ZeroSSL for certificates.
            caddy.tls.dns: "cloudflare $CLOUDFLARE_API_TOKEN" # Use Cloudflare for DNS challenges.
            caddy.tls.protocols: "tls1.3" # Require TLS 1.3.
        networks:
            - caddy
            - gluetun
        ports:
            - ${DEEMIX_PORT:-6595}:6595/tcp # Web interface.
        security_opt:
            - no-new-privileges:true
        volumes:
            - downloads:/downloads
            - deemix:/config
networks:
    caddy:
        driver: bridge
        enable_ipv6: false
        external: true
        name: caddy-network # $ docker network create --ipv6=false caddy-network
    gluetun:
        driver: bridge
        enable_ipv6: false
        external: true
        name: gluetun-network # $ docker network create --ipv6=false gluetun-network

volumes:
    deemix:
        external: true
        name: deemix-volume # $ docker volume create deemix-volume
    downloads:
        name: downloads-volume
        driver_opts:
            device: "${DOWNLOADS_PATH}" # Root path to store downloaded files into.
            o: bind
            type: none
    media-library:
        name: media-library-volume
        driver_opts:
            device: "${MEDIA_LIBRARY_PATH}" # Root path to the media library.
            o: bind
            type: none
