services:
    deemix:
        container_name: "deemix"
        image: "ghcr.io/bambanah/deemix:latest"
        hostname: "deemix"
        restart: "unless-stopped"
        security_opt: ["no-new-privileges:true"]
        environment:
            DEEMIX_SINGLE_USER: true # Use one global user.
            PGID: "${PGID}" # Group ID to run the container as.
            PUID: "${PUID}" # User ID to run the container as.
            TZ: "${TZ}" # Timezone to configure the container to use.
            UMASK_SET: "${UMASK}" # Default umask permissions to apply to newly created files.
        healthcheck:
            interval: "1m"
            retries: "3"
            start_period: "30s"
            test: ["CMD", "curl", "-f", "http://localhost:6595/"]
            timeout: "3s"
        networks:
            - "frontend" # Local frontend network.
            - "media" # Media stack network.
        ports:
            - "${DEEMIX_PORT:-6595}:6595/tcp" # Local web interface.
        volumes:
            - "deemix:/config" # Configuration and data volume.
            - "deemix-downloads:/downloads" # Root Deemix downloads volume.

networks:
    frontend:
        driver: "bridge"
        external: "true"
        name: "frontend-network"
    media:
        driver: "bridge"
        external: "true"
        name: "media-network"

volumes:
    deemix:
        external: "true"
        name: "deemix-volume"
    deemix-downloads:
        name: "deemix-downloads-volume"
        driver_opts:
            device: "${DOWNLOADS_PATH}/deemix"
            o: "bind"
            type: "none"
