services:
  uptime-kuma:
    container_name: uptime-kuma
    image: ghcr.io/louislam/uptime-kuma:2.0.0-beta-rootless.3
    env_file: ../../.env
    hostname: uptime-kuma
    restart: always # Always keep running.
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - caddy # External Caddy/reverse proxy network.
      - frontend # Internal network for local web interface access.
    ports:
      - ${UPTIMEKUMA_WEBUI_PORT:-3001}:3001/tcp # Web interface.
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - socket-proxy:/var/run # Docker socket proxy.
      - uptime-kuma:/app/data # Data directory.
    depends_on:
      socket-proxy:
        condition: service_healthy # Wait for the Docker socket proxy.
    labels:
      caddy: ${PUBLISHED_UPTIMEKUMA_URL} # Tells Caddy to reverse proxy to the external Uptime Kuma URL.
      caddy.reverse_proxy: uptime-kuma:3001 # Tells Caddy to reverse proxy internal traffic on port 3001.
      caddy.tls.ca: https://acme.zerossl.com/v2/DV90 # Use ZeroSSL as the CA issuer.
      caddy.tls.dns: cloudflare $CLOUDFLARE_API_TOKEN # Use Cloudflare for DNS challenges.
      caddy.tls.protocols: tls1.3 # Requires clients to support TLS 1.3.
    security_opt:
      - no-new-privileges:true

networks:
  caddy:
    name: caddy-network
    driver: bridge
    enable_ipv6: false
    external: true
  frontend:
    name: frontend-network
    driver: bridge
    enable_ipv6: false
    external: true

volumes:
  socket-proxy:
    name: socket-proxy-volume
    external: true
  uptime-kuma:
    name: uptime-kuma-volume
    external: true
