services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    env_file: ../../.env
    network_mode: service:gluetun
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - WEBUI_PORT=${QBITTORRENT_WEBUI_PORT}
      - INTERFACE=tun0 # Killswitch; use tun0 only.
      - USER=${QBITTORRENT_USER}
      - PASSWORD=${QBITTORRENT_PASSWORD}
    volumes:
      - qbittorrent:/config
      - ${PATH_DOWNLOADS_DIRECTORY}/downloads:/downloads
      - gluetun:/gluetun:ro
