services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:5.1.0-r0-ls399 # **HEAVY SIGH** https://github.com/qbittorrent/qBittorrent/issues/22909
    env_file: ../../.env
    network_mode: service:gluetun
    restart: unless-stopped
    environment:
      - INTERFACE=tun0 # Killswitch; use tun0 only.
      - WEBUI_PORT=${QBITTORRENT_WEBUI_PORT}
    volumes:
      - ${PATH_DOWNLOADS_DIRECTORY}/downloads:/downloads
      - gluetun:/gluetun:ro
      - qbittorrent:/config
