services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/11notes/qbittorrent:5
    command: --profile=/opt --confirm-legal-notice # stfu legal notice god
    env_file: ../../.env
    network_mode: service:gluetun # Use Gluetun for all networking.
    read_only: true
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - ${DOWNLOADS_DIRECTORY}:/downloads # Root downloads directory; needs to be writable by 1000:1000.
      - qbittorrent:/qbittorrent/etc # qBittorrent configuration.
      - qbittorrent:/qbittorrent/var # qBittorrent database.
    depends_on:
      gluetun:
        condition: service_healthy # Wait for Gluetun to become healthy before starting.
    healthcheck:
      interval: 1m
      retries: 3
      start_period: 1m
      test: [
          "CMD",
          "curl",
          "-f",
          "http://localhost:${QBITTORRENT_WEBUI_PORT:-8080}",
        ]
      timeout: 5s
    security_opt:
      - no-new-privileges:true
