services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:5.1.0-r0-ls399
    network_mode: service:gluetun
    restart: unless-stopped
    devices:
      - /dev/net/tun:/dev/net/tun
    depends_on:
      gluetun:
        condition: service_started
    env_file:
      - ../../.env
    environment:
      - DOCKER_MODS=ghcr.io/gabe565/linuxserver-mod-vuetorrent # /vuetorrent
      - INTERFACE=tun0 # Killswitch; use tun0 only.
      - WEBUI_PORT=8080
    volumes:
      - ${PATH_DOWNLOADS_DIRECTORY}/torrents:/downloads
      - gluetun:/gluetun:ro
      - qbittorrent:/config
