services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    env_file: ../../.env
    network_mode: service:gluetun
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest # Installs Vuetorrent at /.
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    healthcheck:
      interval: 5m
      retries: 3
      start_period: 2m
      test: ["CMD", "curl", "-f", "http://localhost:8080/"] # Ping the WebUI for a nasty healthcheck.
      timeout: 10s
    labels:
      docker-volume-backup.volume: /config # Tells docker-volume-backup to backup the /config volume.
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    volumes:
      - ${DOWNLOADS_DIRECTORY}:/downloads
      - qbittorrent:/config
