services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    env_file: ../../.env
    network_mode: service:gluetun # Use Gluetun for all networking.
    restart: unless-stopped
    environment:
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest # Automatically installs Vuetorrent at /vuetorrent.
      - PGID=${PGID} # Group ID to run the container under.
      - PUID=${PUID} # User ID to run the container under.
      - TZ=${TZ} # Timezone to run the container under.
      - UMASK=${UMASK} # Default UMASK permissions to set on newly created files.
      - WEBUI_PORT=${QBITTORRENT_WEBUI_PORT:-8080} # qBittorrent WebUI port.
    volumes:
      - ${DOWNLOADS_DIRECTORY}:/downloads # Root path to the downloads directory.
      - qbittorrent:/config # qBittorrent configuration and data path/volume.
    depends_on:
      gluetun:
        condition: service_healthy # Wait for Gluetun to become healthy before starting.
    healthcheck:
      interval: 5m
      retries: 3
      start_period: 2m
      test: [
          "CMD",
          "curl",
          "-f",
          "http://localhost:${QBITTORRENT_WEBUI_PORT:-8080}",
        ] # Check to see if the qBittorrent WebUI is connectable.
      timeout: 10s
    security_opt:
      - no-new-privileges:true # Do not allow privilege escalation.

volumes:
  qbittorrent:
    name: qbittorrent-volume # qBittorrent configuration and data path/volume.
    external: true
