services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:5.1.0-r0-ls399 # https://github.com/qbittorrent/qBittorrent/issues/22909
    restart: unless-stopped
    devices:
      - /dev/net/tun:/dev/net/tun
    depends_on:
      gluetun:
        condition: service_healthy
    env_file:
      - ../../.env
    environment:
      - INTERFACE=tun0 # Killswitch; use tun0 only.
      - WEBUI_PORT=${QBITTORRENT_WEBUI_PORT}
    network_mode: service:gluetun
    volumes:
      - ${PATH_DOWNLOADS_DIRECTORY}/torrents:/downloads
      - qbittorrent:/config

  qbittorrent-natmap:
    image: ghcr.io/soxfor/qbittorrent-natmap:latest
    container_name: qbittorrent-natmap
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
      qbittorrent:
        condition: service_started
    network_mode: service:gluetun
    environment:
      - QBITTORRENT_PASS=${QBITTORRENT_WEBUI_USER}
      - QBITTORRENT_PORT=${QBITTORRENT_WEBUI_PORT}
      - QBITTORRENT_SERVER=${WIREGUARD_ADDRESSES}
      - QBITTORRENT_USER=${QBITTORRENT_WEBUI_USER}
      - VPN_GATEWAY=${VPN_DNS_ADDRESS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
