---
services:
    ###############################################################################
    # The Lounge: Web based IRC client.                                           #
    ##############################################################################

    thelounge:
        image: lscr.io/linuxserver/thelounge:latest
        container_name: thelounge
        hostname: thelounge
        restart: unless-stopped
        environment:
            PGID: "${PGID}" # Local group to run as.
            PUID: "${PUID}" # Local user to run as.
            TZ: "${TZ}" # Configures the timezone to use.
            UMASK: "${UMASK}" # Umask to apply to newly created files.
        healthcheck:
            interval: 1m
            start_period: 30s
            test: "curl -f http://127.0.0.1:9000 || exit 1"
        labels:
            caddy: "${THELOUNGE_URL}" # Reverse proxy traffic to the published URL.
            caddy.import: "external thelounge:9000" # Reverse proxy internal traffic.
            caddy.tls.ca: "https://acme.zerossl.com/v2/DV90" # Use ZeroSSL for certificates.
            caddy.tls.dns: "cloudflare $CLOUDFLARE_API_TOKEN" # Use Cloudflare for DNS challenges.
            caddy.tls.protocols: "tls1.3" # Require TLS 1.3.
        networks:
            - caddy
        ports:
            - ${THELOUNGE_PORT:-9000}:9000/tcp # Web interface.
        security_opt:
            - no-new-privileges:true
        volumes:
            - thelounge:/config # The Lounge configuration and database volume.

networks:
    caddy:
        driver: bridge
        enable_ipv6: false
        external: true
        name: caddy-network # $ docker network create --ipv6=false caddy-network

volumes:
    thelounge:
        driver_opts:
            device: "${THELOUNGE_DATA_PATH}" # Root path to store The Lounge data.
            o: bind
            type: none
