services:
    checkmate:
        container_name: checkmate
        image: ghcr.io/bluewave-labs/checkmate-backend-mono:v3.1.5
        restart: unless-stopped
        environment:
            CLIENT_HOST: http://localhost # Checkmate client host.
            DB_CONNECTION_STRING: mongodb://checkmate-db:27017/uptime_db # Checkmate database connecton URL.
            DOCKER_HOST: tcp://socket-proxy:2375 # Connect to the Docker socket proxy.
            JWT_SECRET: ${CHECKMATE_JWT} # JWT to use to secure Checkmate.
            UPTIME_APP_API_BASE_URL: http://localhost:52345/api/v1 # Checkmate API URL.
            UPTIME_APP_CLIENT_HOST: http://localhost # Checkmate API host.
        networks:
            - frontend
            - internal
        ports:
            - ${CHECKMATE_PORT:-52345}:52345/tcp # Checkmate web interface.
        depends_on:
            checkmate-db:
                condition: service_healthy # Require Checkmate's database to be healthy before connecting.
                restart: true
        security_opt:
            - no-new-privileges:true

    checkmate-capture:
        container_name: checkmate-capture
        image: ghcr.io/bluewave-labs/capture:v1.3.0
        read_only: true
        restart: unless-stopped
        user: ${PUID}:${PGID}
        networks:
            - internal
        environment:
            API_SECRET: ${CHECKMATE_API_SECRET} # Sets the API secret.
        ports:
            - ${CHECKMATE_CAPTURE_PORT:-59232}:59232/tcp
        security_opt:
            - no-new-privileges:true

    checkmate-db:
        container_name: checkmate-db
        image: ghcr.io/bluewave-labs/checkmate-mongo:v3.1.5
        command: ["mongod", "--quiet", "--bind_ip_all"]
        restart: unless-stopped
        networks:
            - internal
        volumes:
            - checkmate-db:/data/db # Checkmate database.
        healthcheck:
            interval: 1m
            retries: 3
            start_period: 15s
            test:
                [
                    "CMD",
                    "mongosh",
                    "--eval",
                    "db.adminCommand('ping')",
                    "--quiet",
                ]
            timeout: 30s
        security_opt:
            - no-new-privileges:true

volumes:
    checkmate-db:
        external: true
        name: checkmate-db-volume
