---
# Default alerts.
x-defaults-alerts: &defaults-alerts
  - type: discord
    send-on-resolved: true

# Default conditions.
x-defaults-conditions: &defaults-conditions
  - "[STATUS] == 200"
  - "[RESPONSE_TIME] < 1000"

# Default options.
x-defaults: &defaults
  alerts: *defaults-alerts
  conditions: *defaults-conditions
  interval: 5m

# Default HTTP (with certs) options.
x-defaults-http: &defaults-http
  <<: *defaults
  conditions:
    - "[CERTIFICATE_EXPIRATION] > 240h"
    - "[DOMAIN_EXPIRATION] > 720h"
    - "[STATUS] == 200"
    - "[RESPONSE_TIME] < 3000"

# Default container options.
x-defaults-container: &defaults-container
  <<: *defaults
  conditions:
    - "[BODY].State.Health.Status != unhealthy"
    - "[STATUS] == 200"
    - "[RESPONSE_TIME] < 1000"
  ui:
    hide-hostname: true

# Alerting configuration.
alerting:
  discord:
    title: "🚨 Status Update"
    webhook-url: "${ALERTS_DISCORD_WEBHOOK_URL}"

# Storage configuration.
storage:
  type: postgres
  path: "postgres://gatus:gatus@gatus-db:5432/gatus?sslmode=disable"

# UI configuration.
ui:
  default-sort-by: group
  header: ${GATUS_HEADER}
  link: "${GATUS_URL}"
  logo: "${GATUS_LOGO_URL}"
  title: ${GATUS_TITLE}

endpoints:
  ###########################################################################
  # External apps.                                                          #
  ###########################################################################

  # Chhoto.
  - name: Chhoto URL Shortener
    <<: *defaults
    group: External
    url: https://${CHHOTO_URL}

  # Jellyfin.
  - name: Jellyfin
    <<: *defaults
    group: External
    url: https://${JELLYFIN_URL}/health

  # OpenCloud.
  - name: OpenCloud
    <<: *defaults
    group: External
    url: https://${OPENCLOUD_URL}

  # The Lounge.
  - name: The Lounge
    <<: *defaults
    group: External
    url: https://${THELOUNGE_URL}

  # Vaultwarden.
  - name: Vaultwarden
    <<: *defaults
    group: External
    url: https://${VAULTWARDEN_URL}/alive

  # Website.
  - name: Website - HTTP
    <<: *defaults-http
    group: External
    url: https://${DOMAIN}

  ###########################################################################
  # Infrastructure.                                                         #
  ###########################################################################

  # Caddy.
  - name: Caddy
    <<: *defaults-container
    group: Internal Infrastructure
    url: ${SOCKET_PROXY_URL}/containers/caddy/json

  # Beszel.
  - name: Beszel
    <<: *defaults-container
    group: Internal Infrastructure
    url: ${SOCKET_PROXY_URL}/containers/beszel/json

  # Beszel Agent.
  - name: Beszel Agent
    <<: *defaults-container
    group: Internal Infrastructure
    url: ${SOCKET_PROXY_URL}/containers/beszel-agent/json

  # Dozzle.
  - name: Dozzle
    <<: *defaults-container
    group: Internal Infrastructure
    url: ${SOCKET_PROXY_URL}/containers/dozzle/json

  # Socket Proxy.
  - name: Socket Proxy
    <<: *defaults-container
    group: Internal Infrastructure
    url: ${SOCKET_PROXY_URL}/containers/socket-proxy/json

  ###########################################################################
  # Media management.                                                       #
  ###########################################################################

  # Byparr.
  - name: Byparr
    <<: *defaults-container
    group: Media Management
    url: ${SOCKET_PROXY_URL}/containers/byparr/json

  # Cleanuparr.
  - name: Cleanuparr
    <<: *defaults-container
    group: Media Management
    url: ${SOCKET_PROXY_URL}/containers/cleanuparr/json

  # Gluetun.
  - name: Gluetun
    <<: *defaults-container
    group: Media Management
    url: ${SOCKET_PROXY_URL}/containers/gluetun/json

  # Huntarr.
  - name: Huntarr
    <<: *defaults-container
    group: Media Management
    url: ${SOCKET_PROXY_URL}/containers/huntarr/json

  # LazyLibrarian.
  - name: LazyLibrarian
    <<: *defaults-container
    group: Media Management
    url: ${SOCKET_PROXY_URL}/containers/lazylibrarian/json

  # Lidarr.
  - name: Lidarr
    <<: *defaults-container
    group: Media Management
    url: ${SOCKET_PROXY_URL}/containers/lidarr/json

  # mam-ip-helper
  - name: MyAnonaMouse IP
    <<: *defaults-container
    group: Media Management
    url: ${SOCKET_PROXY_URL}/containers/mam-ip-helper/json

  # Profilarr.
  - name: Profilarr
    <<: *defaults-container
    group: Media Management
    url: ${SOCKET_PROXY_URL}/containers/profilarr/json

  # Prowlarr.
  - name: Prowlarr
    <<: *defaults-container
    group: Media Management
    url: ${SOCKET_PROXY_URL}/containers/prowlarr/json

  # qBittorrent.
  - name: qBittorrent
    <<: *defaults-container
    group: Media Management
    url: ${SOCKET_PROXY_URL}/containers/qbittorrent/json

  # Radarr.
  - name: Radarr
    <<: *defaults-container
    group: Media Management
    url: ${SOCKET_PROXY_URL}/containers/radarr/json

  # slskd.
  - name: slskd
    <<: *defaults-container
    group: Media Management
    url: ${SOCKET_PROXY_URL}/containers/slskd/json

  # Sonarr.
  - name: Sonarr
    <<: *defaults-container
    group: Media Management
    url: ${SOCKET_PROXY_URL}/containers/sonarr/json

  # Unpackerr.
  - name: Unpackerr
    <<: *defaults-container
    group: Media Management
    url: ${SOCKET_PROXY_URL}/containers/unpackerr/json
