services:
  deemix:
    container_name: deemix
    image: ghcr.io/bambanah/deemix:latest
    network_mode: service:gluetun
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
    env_file:
      - ../../.env
    environment:
      - DEEMIX_SINGLE_USER=true
      - PGID=${PGID}
      - PUID=${PUID}
      - UMASK=022
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6595/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${PATH_DOWNLOADS_DIRECTORY}/deemix:/downloads
      - deemix:/config
