services:
  deemix:
    container_name: deemix
    image: ghcr.io/bambanah/deemix:latest
    env_file: ../../.env
    network_mode: service:gluetun # Only connect to the VPN network.
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    depends_on:
      gluetun:
        condition: service_healthy # Do not start unless Gluetun is healthy.
    environment:
      - DEEMIX_SINGLE_USER=true # Enables single-user mode.
      - PGID=${PGID} # Group ID to run under.
      - PUID=${PUID} # User ID to run under.
      - TZ=${TZ} # Timezone to run with.
      - UMASK_SET=${UMASK} # Default umask permissions to set.
    healthcheck:
      interval: 5m
      retries: 3
      start_period: 1m
      test: ["CMD", "curl", "-f", "http://localhost:6595/"] # Ping the WebUI.
      timeout: 10s
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    volumes:
      - ${ROOT_DOWNLOADS_DIRECTORY}:/downloads # Root path to the downloads directory.
      - deemix:/config # Deemix data volume.
