services:
    cleanuparr:
        container_name: "cleanuparr"
        image: "ghcr.io/cleanuparr/cleanuparr:latest"
        hostname: "cleanuparr"
        restart: "unless-stopped"
        security_opt: ["no-new-privileges:true"]
        environment:
            PGID: "${PGID}" # Group ID to run the container as.
            PUID: "${PUID}" # User ID to run the container as.
            TZ: "${TZ}" # Timezone to configure the container to use.
        networks:
            - "frontend" # Local frontend network.
            - "gluetun" # Gluetun VPN network.
            - "media" # Media stack network.
        ports:
            - "${CLEANUPARR_PORT:-11011}:11011/tcp" # Local web interface.
        volumes:
            - cleanuparr:/config # Configuration and data volume.

networks:
    frontend:
        driver: "bridge"
        external: "true"
        name: "frontend-network"
    gluetun:
        driver: "bridge"
        external: "true"
        name: "gluetun-network"
    media:
        driver: "bridge"
        external: "true"
        name: "media-network"
volumes:
    cleanuparr:
        external: "true"
        name: "cleanuparr-volume"
