services:
    cleanuparr:
        container_name: "cleanuparr"
        image: "ghcr.io/cleanuparr/cleanuparr:latest"
        hostname: "cleanuparr"
        restart: "unless-stopped"
        security_opt: ["no-new-privileges:true"]
        environment:
            PGID: "${PGID}" # Group ID to run the container as.
            PUID: "${PUID}" # User ID to run the container as.
            TZ: "${TZ}" # Timezone to configure the container to use.
        healthcheck:
            interval: "1m"
            retries: "3"
            start_period: "30s"
            test: ["CMD", "curl", "-f", "http://localhost:11011/health"]
            timeout: "3s"
        networks:
            - "frontend" # Local frontend network.
            - "media" # Media stack network.
        ports:
            - "${CLEANUPARR_PORT:-11011}:11011/tcp" # Local web interface.
        volumes:
            - cleanuparr:/config # Configuration and data volume.

networks:
    frontend:
        driver: "bridge"
        external: "true"
        name: "frontend-network"
    media:
        driver: "bridge"
        external: "true"
        name: "media-network"

volumes:
    cleanuparr:
        external: "true"
        name: "cleanuparr-volume"
