services:
    bookshelf:
        container_name: bookshelf
        image: ghcr.io/pennydreadful/bookshelf:hardcover
        restart: unless-stopped
        environment:
            PGID: ${PGID}
            PUID: ${PUID}
            TZ: ${TZ}
            UMASK: ${UMASK}
        network_mode: service:gluetun # Route all networking through Gluetun.
        volumes:
            - bookshelf:/config # Configuration and data volume.
            - downloads:/downloads # Root downloads volume.
            - media-library:/library # Root media library volume.
        depends_on:
            gluetun:
                condition: service_healthy # Require Gluetun to be healthy before connecting.
                restart: true
        healthcheck:
            interval: 1m
            retries: 3
            start_period: 15s
            test: ["CMD", "curl", "-f", "http://localhost:8787/health"]
            timeout: 3s
        security_opt:
            - no-new-privileges:true

volumes:
    bookshelf:
        external: true
        name: bookshelf-volume
