services:
    bookshelf:
        container_name: bookshelf
        image: ghcr.io/pennydreadful/bookshelf:hardcover
        restart: unless-stopped
        environment:
            PGID: ${PGID}
            PUID: ${PUID}
            TZ: ${TZ}
            UMASK: ${UMASK}
        networks:
            - gluetun
            - media
        ports:
            - ${BOOKSHELF_PORT:-8787}:8787/tcp # Bookshelf web interface.
        volumes:
            - bookshelf:/config # Configuration and data volume.
            - media-library:/library # Root media library volume.
        healthcheck:
            interval: 1m
            retries: 3
            start_period: 15s
            test: ["CMD", "curl", "-f", "http://localhost:8787/health"]
            timeout: 3s
        security_opt:
            - no-new-privileges:true

volumes:
    bookshelf:
        external: true
        name: bookshelf-volume
