---
services:
    ###########################################################################
    # Uptime Kuma: Uptime monitoring, notifications, and status page.         #
    ###########################################################################

    uptime-kuma:
        image: ghcr.io/louislam/uptime-kuma:2.0.0-beta-rootless.4
        container_name: uptime-kuma
        user: ${PUID}:${PGID}
        hostname: uptime-kuma
        restart: unless-stopped
        depends_on:
            socket-proxy:
                condition: service_healthy
                restart: true
        environment:
            DOCKER_HOST: "tcp://socket-proxy:2375" # Connect to the socket proxy.
            PGID: "${PGID}" # Local group to run as.
            PUID: "${PUID}" # Local user to run as.
            UPTIME_KUMA_PORT: "${UPTIME_KUMA_PORT:-3001}" # Configures the port to use.
        labels:
            caddy: "${UPTIME_KUMA_URL}" # Reverse proxy traffic to the published URL.
            caddy.import: "external uptime-kuma:${UPTIME_KUMA_PORT:-3001}" # Reverse proxy internal traffic.
            caddy.tls.ca: "https://acme.zerossl.com/v2/DV90" # Use ZeroSSL for certificates.
            caddy.tls.dns: "cloudflare $CLOUDFLARE_API_TOKEN" # Use Cloudflare for DNS challenges.
            caddy.tls.protocols: "tls1.3" # Require TLS 1.3.
        networks:
            - caddy
            - socket-proxy
        ports:
            - ${UPTIME_KUMA_PORT:-3001}:${UPTIME_KUMA_PORT:-3001}/tcp # Web interface.
        security_opt:
            - no-new-privileges:true
        volumes:
            - uptime-kuma:/app/data

networks:
    caddy:
        driver: bridge
        enable_ipv6: false
        external: true
        name: caddy-network # $ docker network create --ipv6=false caddy-network
    socket-proxy:
        driver: bridge
        enable_ipv6: false
        external: true # $ docker network create --ipv6=false socket-proxy-network
        internal: true # Isolates the network from the outside.
        name: socket-proxy-network # Internal-only network used only for Socket Proxy traffic.

volumes:
    uptime-kuma:
        external: true
        name: uptime-kuma-volume # Uptime Kuma configuration and database.
