services:
  gluetun:
    container_name: gluetun
    image: ghcr.io/qdm12/gluetun:v3.40.0
    env_file: ../../.env
    restart: unless-stopped
    devices:
      - /dev/net/tun:/dev/net/tun # TUN/TAP network device passthrough.
    environment:
      - FIREWALL_OUTBOUND_SUBNETS=${FIREWALL_OUTBOUND_SUBNETS:-172.20.0.0/16,192.168.1.0/24} # List of subnets allowed to bypass firewall traffic.
      - PORT_FORWARD_ONLY=true # Only connect to servers with port forwarding enabled.
      - SERVER_COUNTRIES=${SERVER_COUNTRIES:-Switzerland} # List of countries to connect to.
      - UPDATER_PERIOD=24h # Check for updated server information every 24 hours.
      - VPN_PORT_FORWARDING=on # Enable VPN port forwarding.
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:-protonvpn} # The VPN service provider to use.
      - VPN_TYPE=wireguard # Use Wireguard instead of OpenVPN.
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY} # WireGuard private key to authenticate to the service provider with.
    networks:
      - frontend # Internal network for local web interface access.
      - gluetun # Gluetun VPN network.
    ports:
      - ${QBITTORRENT_WEBUI_PORT:-8080}:${QBITTORRENT_WEBUI_PORT:-8080} # qBittorrent WebUI port.
    volumes:
      - gluetun:/gluetun # Gluetun configuration volume.
    cap_add:
      - NET_ADMIN # Required for configuring networking.
    security_opt:
      - no-new-privileges:true

networks:
  frontend:
    name: frontend-network
    driver: bridge
    enable_ipv6: false
    external: true
  gluetun:
    name: gluetun-network
    driver: bridge
    enable_ipv6: false
    external: true

volumes:
  gluetun:
    name: gluetun-volume
    external: true
