services:
  gluetun:
    container_name: gluetun
    image: ghcr.io/qdm12/gluetun:v3
    env_file: ../../.env
    hostname: gluetun
    restart: unless-stopped
    devices:
      - /dev/net/tun:/dev/net/tun # TUN/TAP network device passthrough.
    environment:
      - FIREWALL_OUTBOUND_SUBNETS=${FIREWALL_OUTBOUND_SUBNETS:-172.20.0.0/16} # List of subnets allowed to bypass firewall traffic.
      - PORT_FORWARD_ONLY=true # Only connect to servers with port forwarding enabled.
      - SERVER_COUNTRIES=${SERVER_COUNTRIES:-Switzerland} # List of countries to connect to.
      - UPDATER_PERIOD=8h # Check for updated server information every 8 hours.
      - VPN_PORT_FORWARDING=on # Enable VPN port forwarding.
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:-protonvpn} # The VPN service provider to use.
      - VPN_TYPE=wireguard # Use Wireguard for VPN connections.
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY} # WireGuard private key to authenticate to the service provider with.
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1' # Attempt to update qBittorrent port; local auth bypass needs to be on.
    networks:
      - gluetun
      - internal
    ports:
      - ${QBITTORRENT_WEBUI_PORT:-8080}:${QBITTORRENT_WEBUI_PORT:-8080} # Local qBittorrent web interface.
    volumes:
      - gluetun:/gluetun # Gluetun configuration volume.
    cap_add:
      - NET_ADMIN # Required for configuring networking.
    security_opt:
      - no-new-privileges:true
