services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:latest
    restart: unless-stopped
    env_file:
      - ../../.env
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - FIREWALL_OUTBOUND_SUBNETS=172.20.0.0/16,192.168.1.0/24
      - UPDATER_PERIOD=24h
      - VPN_DNS_ADDRESS=${VPN_DNS_ADDRESS}
      - VPN_ENDPOINT_IP=${VPN_ENDPOINT_IP}
      - VPN_ENDPOINT_PORT=${VPN_ENDPOINT_PORT}
      - VPN_PORT_FORWARDING_PROVIDER=${VPN_PROVIDER}
      - VPN_PORT_FORWARDING=on
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
    healthcheck:
      interval: 15s
      retries: 3
      start_period: 60s
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      timeout: 5s
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    ports:
      - ${QBITTORRENT_WEBUI_PORT}:${QBITTORRENT_WEBUI_PORT}
      - 8000:8000
    security_opt:
      - no-new-privileges:true
    volumes:
      - gluetun:/gluetun
