services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:latest
    env_file: ../../.env
    restart: unless-stopped
    devices:
      - /dev/net/tun:/dev/net/tun # TUN/TAP network device passthrough.
    environment:
      - FIREWALL_OUTBOUND_SUBNETS=${FIREWALL_OUTBOUND_SUBNETS:-172.20.0.0/16,192.168.1.0/24} # List of subnets allowed to bypass firewall traffic.
      - PORT_FORWARD_ONLY=true # Only connect to servers with port forwarding enabled.
      - SERVER_COUNTRIES=${SERVER_COUNTRIES:-Switzerland} # List of countries to connect to.
      - UPDATER_PERIOD=24h # Check for updated server information every 24 hours.
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1' # Attempt to update qBittorrent port; local auth bypass needs to be on.
      - VPN_PORT_FORWARDING=on # Enable VPN port forwarding.
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:-protonvpn} # The VPN service provider to use.
      - VPN_TYPE=wireguard # Use Wireguard instead of OpenVPN.
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY} # WireGuard private key to authenticate to the service provider with.
    networks:
      - gluetun # Gluetun VPN network.
    ports:
      - ${QBITTORRENT_WEBUI_PORT:-8080}:${QBITTORRENT_WEBUI_PORT:-8080} # qBittorrent WebUI port.
    volumes:
      - gluetun:/gluetun # Gluetun configuration volume.
    cap_add:
      - NET_ADMIN # Required for configuring networking.
    security_opt:
      - no-new-privileges:true # Do not allow privilege escalation.

networks:
  gluetun:
    name: gluetun-network # Gluetun VPN network.
    driver: bridge
    enable_ipv6: false
    external: true

volumes:
  gluetun:
    name: gluetun-volume # Gluetun configuration volume.
    external: true
