services:
  gluetun:
    container_name: gluetun
    env_file: ../../.env
    image: qmcgaw/gluetun:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - FIREWALL_OUTBOUND_SUBNETS=${GLUETUN_VPN_OUTBOUND_SUBNETS}
      - UPDATER_PERIOD=8h
      - VPN_DNS_ADDRESS=${GLUETUN_VPN_DNS_ADDRESS}
      - VPN_ENDPOINT_IP=${GLUETUN_VPN_ENDPOINT_IP}
      - VPN_ENDPOINT_PORT=${GLUETUN_VPN_ENDPOINT_PORT}
      - VPN_PORT_FORWARDING_PROVIDER=${GLUETUN_VPN_PROVIDER}
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\\\"listen_port\\\":{{PORTS}}}" "http://127.0.0.1:${QBITTORRENT_WEBUI_PORT}/api/v2/app/setPreferences" 2>&1'
      - VPN_PORT_FORWARDING=on
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_ADDRESSES=${GLUETUN_VPN_WIREGUARD_ADDRESSES}
      - WIREGUARD_PRIVATE_KEY=${GLUETUN_VPN_WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_PUBLIC_KEY=${GLUETUN_VPN_WIREGUARD_PUBLIC_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 60s
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    ports:
      - 8000:8000
      - ${QBITTORRENT_WEBUI_PORT}:${QBITTORRENT_WEBUI_PORT}
    volumes:
      - gluetun:/gluetun
