services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:latest
    privileged: true # gluetun is a bit cranky without this
    restart: unless-stopped
    env_file:
      - ../../.env
    cap_add:
      - NET_ADMIN
    environment:
      - FIREWALL_OUTBOUND_SUBNETS=172.20.0.0/16,192.168.1.0/24
      - UPDATER_PERIOD=24h
      - VPN_DNS_ADDRESS=${VPN_DNS_ADDRESS}
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      - VPN_PORT_FORWARDING=on
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - WIREGUARD_ENDPOINT_IP=${WIREGUARD_ENDPOINT_IP}
      - WIREGUARD_ENDPOINT_PORT=${WIREGUARD_ENDPOINT_PORT}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    ports:
      - ${QBITTORRENT_WEBUI_PORT}:${QBITTORRENT_WEBUI_PORT}
      - 8000:8000
    volumes:
      - gluetun:/gluetun
