services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN # Required for configuring networking.
    env_file:
      - ../../.env
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    devices:
      - /dev/net/tun:/dev/net/tun # TUN/TAP network device passthrough.
    environment:
      - FIREWALL_OUTBOUND_SUBNETS=172.20.0.0/16,192.168.1.0/24 # List of subnets allowed to bypass the firewall.
      - PORT_FORWARD_ONLY=true # Only connect to servers with port forwarding enabled.
      - SERVER_COUNTRIES=Switzerland # List of ProtonVPN countries to connect to.
      - UPDATER_PERIOD=1h # Check for updated information every hour.
      - VPN_PORT_FORWARDING=on # Enable port forwarding.
      - VPN_SERVICE_PROVIDER=protonvpn # Use ProtonVPN as the VPN service provider.
      - VPN_TYPE=wireguard # Use WireGuard instead of OpenVPN.
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY} # The WireGuard private key to authenticate to ProtonVPN with.
    ports:
      - 7878:7878/tcp # Radarr Web UI.
      - 8080:8080/tcp # qBittorrent Web UI.
      - 8686:8686/tcp # Lidarr Web UI.
      - 8989:8989/tcp # Sonarr Web UI.
    volumes:
      - gluetun:/gluetun # Gluetun configuration volume.
