services:
    radarr:
        container_name: "radarr"
        image: "lscr.io/linuxserver/radarr:latest"
        hostname: "radarr"
        restart: "unless-stopped"
        security_opt: ["no-new-privileges:true"]
        environment:
            PGID: "${PGID}" # Group ID to run the container as.
            PUID: "${PUID}" # User ID to run the container as.
            TZ: "${TZ}" # Timezone to configure the container to use.
            UMASK: "${UMASK}" # Default umask permissions to apply to newly created files.
        healthcheck:
            interval: "1m"
            retries: "3"
            start_period: "15s"
            test: ["CMD", "curl", "-f", "http://127.0.0.1:7878/ping"]
            timeout: "3s"
        networks:
            - "frontend" # Local frontend network.
            - "gluetun" # Gluetun VPN network.
            - "media" # Media stack network.
        ports:
            - "${RADARR_PORT:-7878}:7878/tcp" # Local web interface.
        volumes:
            - "downloads:/downloads" # Root downloads directory volume.
            - "media-library:/library" # Root media library volume.
            - "radarr:/config" # Configuration and data volume.

networks:
    frontend:
        driver: "bridge"
        external: "true"
        name: "frontend-network"
    gluetun:
        driver: "bridge"
        external: "true"
        name: "gluetun-network"
    media:
        driver: "bridge"
        external: "true"
        name: "media-network"

volumes:
    downloads:
        name: "downloads-volume"
        driver_opts:
            device: "${DOWNLOADS_PATH}" # Root downloads directory path.
            o: "bind"
            type: "none"
    media-library:
        name: "media-library-volume"
        driver_opts:
            device: "${MEDIA_LIBRARY_PATH}" # Root media library path.
            o: "bind"
            type: "none"
    radarr:
        external: "true"
        name: "radarr-volume"
