services:
    radarr:
        container_name: radarr
        image: ghcr.io/11notes/radarr:5
        read_only: true
        restart: unless-stopped
        tmpfs: /tmp:uid=1000,gid=1000 # Required for read-only images.
        environment:
            TZ: ${TZ}
        network_mode: service:gluetun # Route all networking through Gluetun.
        volumes:
            - downloads:/downloads # Root downloads volume.
            - media-library:/library # Root media library volume.
            - radarr:/radarr/etc # Configuration and data volume.
        depends_on:
            gluetun:
                condition: service_healthy # Require Gluetun to be healthy before connecting.
                restart: true
        security_opt:
            - no-new-privileges:true

volumes:
    radarr:
        external: true
        name: radarr-volume
