---
name: media

include:
    - ./downloads/compose.yml # Media download tools.
    - ./management/compose.yml # Media management tools.

services:
    ###########################################################################
    # Jellyfin: Media server.                                                 #
    ###########################################################################

    jellyfin:
        image: ghcr.io/hotio/jellyfin:release
        container_name: jellyfin
        hostname: jellyfin
        restart: unless-stopped
        devices:
            - /dev/dri:/dev/dri # Video device passthrough.
        environment:
            JELLYFIN_PublishedServerUrl: "https://${JELLYFIN_SUBDOMAIN}.${DOMAIN}" # Configures autodiscovery to use the external URL.
            PGID: "${PGID}" # Local group to run as.
            PUID: "${PUID}" # Local user to run as.
            TZ: "${TZ}" # Configures the timezone to use.
            UMASK: "${UMASK}" # Default umask to apply to newly created files.
        expose:
            - 8096/tcp
        networks:
            - caddy
        volumes:
            - jellyfin:/config
            - media-library:/library:ro
        depends_on:
            caddy:
                condition: service_started
                restart: true
        healthcheck:
            test: "curl -f https://${JELLYFIN_SUBDOMAIN}.${DOMAIN}/health || exit 1"
        security_opt:
            - no-new-privileges:true

networks:
    caddy:
        external: true
        name: caddy-network

volumes:
    jellyfin:
        external: true
        name: jellyfin-volume
    media-library:
        name: media-library-volume
        driver_opts:
            device: "${MEDIA_LIBRARY_PATH}"
            o: bind
            type: none
