---
name: media

include:
    - ./downloads/compose.yml # Media download tools.
    - ./management/compose.yml # Media management tools.

services:
    # Jellyfin: Media server.
    jellyfin:
        image: ghcr.io/hotio/jellyfin:release-10.10.7
        container_name: jellyfin
        hostname: jellyfin
        restart: unless-stopped
        devices:
            - /dev/dri:/dev/dri # Video device passthrough.
        environment:
            PGID: "${PGID}" # Local group to run as.
            PUID: "${PUID}" # Local user to run as.
            TZ: "${TZ}" # Configures the timezone to use.
            UMASK: "${UMASK}" # Default umask to apply to newly created files.
        expose:
            - 8096/tcp
        networks:
            - caddy
        volumes:
            - jellyfin:/config
            - jellyfin-cache:/config/cache
            - media-library:/library:ro
        depends_on:
            caddy:
                condition: service_started
                restart: true
        extra_hosts:
            - "${JELLYFIN_URL}:caddy"
        healthcheck:
            test: "curl -f http://127.0.0.1:8096/health || exit 1"
        security_opt:
            - no-new-privileges:true

networks:
    caddy:
        external: true
        name: caddy-network

volumes:
    jellyfin:
        external: true
        name: jellyfin-volume # $ docker volume create jellyfin-volume
    jellyfin-cache:
        external: true
        name: jellyfin-cache-volume # $ docker volume create jellyfin-cache-volume
    media-library:
        name: media-library-bind
        driver_opts:
            device: "${MEDIA_LIBRARY_PATH}" # Root path to the media library.
            o: bind
            type: none
