---
name: media

# Default environment variables.
x-defaults-env: &defaults-env
    PGID: "${PGID}" # Local group to run as.
    PUID: "${PUID}" # Local user to run as.
    TZ: "${TZ}" # Local timezone to use.
    UMASK: "${UMASK}" # Umask to apply to newly created files.

# Default healthcheck options.
x-defaults-healthcheck: &defaults-healthcheck
    interval: 30s
    retries: 3
    start_period: 30s
    timeout: 3s

# Default container options.
x-defaults: &defaults
    restart: unless-stopped
    environment: *defaults-env
    security_opt:
        - no-new-privileges:true # Prevents privilege escalation.

services:
    #############################################
    # Jellyfin: Media server.                   #
    #############################################

    jellyfin:
        <<: *defaults
        image: lscr.io/linuxserver/jellyfin:latest
        container_name: jellyfin
        hostname: jellyfin
        restart: unless-stopped
        devices:
            - /dev/dri/renderD128:/dev/dri/renderD128 # Video device support; renderD128 is GPU0.
        environment:
            <<: *defaults-env
            DOCKER_MODS: "linuxserver/mods:jellyfin-opencl-intel:latest" # Enables the latest OpenCL drivers.
            JELLYFIN_PublishedServerUrl: "https://${JELLYFIN_URL}" # Configures autodiscovery to use the external URL.
        labels:
            caddy: "${JELLYFIN_URL}" # Tells Caddy to reverse proxy to the external Jellyfin URL.
            caddy.reverse_proxy: "jellyfin:8096" # Tells Caddy to reverse proxy internal traffic on port 8096.
            caddy.tls.ca: "https://acme.zerossl.com/v2/DV90" # Use ZeroSSL as the CA issuer.
            caddy.tls.dns: cloudflare $CLOUDFLARE_API_TOKEN # Use Cloudflare for DNS challenges.
            caddy.tls.protocols: "tls1.3" # Requires clients to support TLS 1.3.
        healthcheck:
            <<: *defaults-healthcheck
            test: "curl -f http://127.0.0.1:8096/health || exit 1"
        networks:
            - caddy # External Caddy network; reverse proxied.
        ports:
            - ${JELLYFIN_PORT:-8096}:8096/tcp # Jellyfin web interface.
        volumes:
            - media-library:/library:ro # Root path to the media library.
            - jellyfin-cache:/config/cache # Jellyfin cache.
            - jellyfin:/config # Jellyfin configuration and database.

    #############################################
    # Gluetun: VPN client.                      #
    #############################################

    gluetun:
        image: ghcr.io/qdm12/gluetun:v3.39.1
        container_name: gluetun
        hostname: gluetun
        cap_add:
            - NET_ADMIN # Required for Wireguard configuration.
        devices:
            - /dev/net/tun:/dev/net/tun # TUN/TAP device passthrough.
        environment:
            <<: *defaults-env
            BLOCK_MALICIOUS: "off" # https://github.com/qdm12/gluetun/issues/765
            DOT: "off" # Disable DoT due to Gluetun issues.
            FIREWALL_OUTBOUND_SUBNETS: "${FIREWALL_OUTBOUND_SUBNETS}" # List of local subnets allowed to access the gluetun network.
            FIREWALL_VPN_INPUT_PORTS: "${FIREWALL_VPN_INPUT_PORTS}" # Ports to use for server-side VPN forwarding; provided by VPN service provider.
            HEALTH_VPN_DURATION_INITIAL: "60s" # https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/healthcheck.md
            PORT_FORWARD_ONLY: "${PORT_FORWARD_ONLY}" # If on, only connect to P2P servers.
            SERVER_CITIES: "${SERVER_CITIES}" # VPN server cities to connect to.
            SERVER_COUNTRIES: "${SERVER_COUNTRIES}" # VPN server countries to connect to.
            SERVER_REGIONS: "${SERVER_REGIONS}" # VPN server regions to connect to.
            UPDATER_PERIOD: "24h" # Update server data every 24 hours.
            VPN_PORT_FORWARDING_UP_COMMAND: /bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1' # Attempt to update qBittorrent port; local auth bypass needs to be on. Edit port above if need be.
            VPN_PORT_FORWARDING: "${VPN_PORT_FORWARDING}" # If on, enables P2P port forwarding.
            VPN_SERVICE_PROVIDER: "${VPN_SERVICE_PROVIDER}" # https://github.com/qdm12/gluetun-wiki/tree/main/setup/providers
            VPN_TYPE: "wireguard" # Use Wireguard for VPN connections.
            WIREGUARD_ADDRESSES: "${WIREGUARD_ADDRESSES}" # Addresses to use for Wireguard.
            WIREGUARD_ENDPOINT_PORT: "${WIREGUARD_ENDPOINT_PORT}" # Port to use for Wireguard.
            WIREGUARD_MTU: "1280" # Use a lower MTU for stability/performance.
            WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL: "25s" # Keep Wireguard alive a little longer.
            WIREGUARD_PRESHARED_KEY: "${WIREGUARD_PRESHARED_KEY}" # Preshared key from the VPN provider's configuration file.
            WIREGUARD_PRIVATE_KEY: "${WIREGUARD_PRIVATE_KEY}" # PrivateKey from the VPN provider's configuration file.
            WIREGUARD_PUBLIC_KEY: "${WIREGUARD_PUBLIC_KEY}" # PublicKey from the VPN provider's configuration file.
        networks:
            - gluetun # Gluetun VPN network.
        ports:
            - ${PROWLARR_PORT:-9696}:9696/tcp # Prowlarr web interface.
            - ${QBITTORRENT_PORT:-8080}:${QBITTORRENT_PORT:-8080}/tcp # qBittorrent web interface.
        security_opt:
            - no-new-privileges:true # Prevents privilege escalation.
        volumes:
            - gluetun:/gluetun # Gluetun configuration.

    #############################################
    # qBittorrent: BitTorrent client.           #
    #############################################

    qbittorrent:
        <<: *defaults
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        network_mode: service:gluetun # Route all traffic through Gluetun.
        depends_on:
            gluetun:
                condition: service_healthy # Require Gluetun to be healthy before connecting.
                restart: true
        environment:
            <<: *defaults-env
            DOCKER_MODS: "ghcr.io/gabe565/linuxserver-mod-vuetorrent" # Auto-install Vuetorrent to /vuetorrent.
            WEBUI_PORT: "${QBITTORRENT_PORT:-8080}" # Sets the web interface port.
        healthcheck:
            <<: *defaults-healthcheck
            test: "curl -f http://127.0.0.1:${QBITTORRENT_PORT:-8080} || exit 1"
        volumes:
            - downloads:/downloads # Root path to store downloaded files into.
            - qbittorrent:/config # qBittorrent configuration and database.

    #############################################
    # Deemix: Deezer music downloader.          #
    #############################################

    deemix:
        <<: *defaults
        image: ghcr.io/bambanah/deemix:latest
        container_name: deemix
        environment:
            <<: *defaults-env
            DEEMIX_SINGLE_USER: "true" # Use one global user.
            UMASK_SET: "${UMASK}" # Umask to apply to newly created files.
        healthcheck:
            <<: *defaults-healthcheck
            test: "curl -f http://127.0.0.1:6595 || exit 1"
        networks:
            - gluetun # Gluetun VPN network; internal-only.
        ports:
            - ${DEEMIX_PORT:-6595}:6595/tcp # Deemix web interface.
        volumes:
            - downloads:/downloads # Root path to store downloaded files into.
            - deemix:/config # Deemix configuration volume.

    #############################################
    # Lidarr: Music manager and organizer.      #
    #############################################

    lidarr:
        <<: *defaults
        image: ghcr.io/hotio/lidarr:pr-plugins
        container_name: lidarr
        healthcheck:
            <<: *defaults-healthcheck
            test: "curl -f http://127.0.0.1:8686/ping || exit 1"
        networks:
            - gluetun # Gluetun VPN network; internal-only.
        ports:
            - ${LIDARR_PORT:-6595}:8686/tcp # Lidarr web interface.
        volumes:
            - downloads:/downloads # Root path to store downloaded files into.
            - lidarr:/config # Lidarr configuration and database.
            - media-library:/library # Root path to the media library.

    #############################################
    # Radarr: Movie manager and PVR.            #
    #############################################

    radarr:
        <<: *defaults
        image: lscr.io/linuxserver/radarr:latest
        container_name: radarr
        healthcheck:
            <<: *defaults-healthcheck
            test: "curl -f http://127.0.0.1:7878/ping || exit 1"
        networks:
            - gluetun # Gluetun VPN network; internal-only.
        ports:
            - ${RADARR_PORT:-7878}:7878/tcp # Radarr web interface.
        volumes:
            - downloads:/downloads # Root path to store downloaded files into.
            - media-library:/library # Root path to the media library.
            - radarr:/config # Radarr configuration and database.

    #############################################
    # Readarr: Book manager and PVR.            #
    #############################################

    readarr:
        <<: *defaults
        image: ghcr.io/pennydreadful/bookshelf:hardcover
        container_name: readarr
        healthcheck:
            <<: *defaults-healthcheck
            test: "curl -f http://127.0.0.1:8787/ping || exit 1"
        networks:
            - gluetun # Gluetun VPN network; internal-only.
        ports:
            - ${READARR_PORT:-8787}:8787/tcp # Readarr web interface.
        volumes:
            - downloads:/downloads # Root path to store downloaded files into.
            - media-library:/library # Root path to the media library.
            - readarr:/config # Readarr configuration and database.

    #############################################
    # Sonarr: TV/Anime manager and PVR.         #
    #############################################

    sonarr:
        <<: *defaults
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr
        healthcheck:
            <<: *defaults-healthcheck
            test: "curl -f http://127.0.0.1:8989/ping || exit 1"
        networks:
            - gluetun # Gluetun VPN network; internal-only.
        ports:
            - ${SONARR_PORT:-8989}:8989/tcp # Sonarr web interface.
        volumes:
            - downloads:/downloads # Root path to store downloaded files into.
            - media-library:/library # Root path to the media library.
            - sonarr:/config # Sonarr configuration and database.

    #############################################
    # Prowlarr: Indexer and tracker manager.    #
    #############################################

    prowlarr:
        <<: *defaults
        image: lscr.io/linuxserver/prowlarr:latest
        container_name: prowlarr
        network_mode: service:gluetun # Route all networking through Gluetun.
        depends_on:
            gluetun:
                condition: service_healthy # Require Gluetun to be healthy before connecting.
                restart: true
        environment:
            <<: *defaults-env
        healthcheck:
            <<: *defaults-healthcheck
            test: "curl -f http://127.0.0.1:9696/ping || exit 1"
        volumes:
            - prowlarr:/config # Prowlarr configuration volume.

    #############################################
    # Flaresolverr: Bypass Cloudflare captchas. #
    #############################################

    flaresolverr:
        <<: *defaults
        image: ghcr.io/flaresolverr/flaresolverr:latest
        container_name: flaresolverr
        user: ${PUID}:${PGID}
        environment:
            <<: *defaults-env
        healthcheck:
            <<: *defaults-healthcheck
            test: "curl -f http://127.0.0.1:8191/health || exit 1"
        networks:
            - gluetun # Gluetun VPN network; internal-only.
        ports:
            - ${FLARESOLVERR_PORT:-8191}:8191/tcp # Flaresolverr server.

    #############################################
    # Profilarr: Profile manager for 'ARR apps. #
    #############################################

    profilarr:
        <<: *defaults
        image: santiagosayshey/profilarr:latest
        container_name: profilarr
        networks:
            - gluetun # Gluetun VPN network; internal-only.
        volumes:
            - profilarr:/config # Profilarr configuration and database.
        ports:
            - ${PROFILARR_PORT:-6868}:6868/tcp # Profilarr web interface.

    #############################################
    # Cleanuparr: Automatically clean ARR apps. #
    #############################################

    cleanuparr:
        <<: *defaults
        image: ghcr.io/cleanuparr/cleanuparr:2
        container_name: cleanuparr
        networks:
            - gluetun # Gluetun VPN network; internal-only.
        volumes:
            - cleanuparr:/config # Cleanuparr configuration and database.
        ports:
            - ${CLEANUPARR_PORT:-11011}:11011/tcp # Cleanuparr web interface.

    #############################################
    # Unpackerr: Automatic download extraction. #
    #############################################

    unpackerr:
        <<: *defaults
        image: ghcr.io/unpackerr/unpackerr:0
        container_name: unpackerr
        restart: unless-stopped
        networks:
            - gluetun # Gluetun VPN network; internal-only.
        environment:
            <<: *defaults-env
            UN_LOG_FILE: "/downloads/unpackerr.log" # Log file location.
            UN_RADARR_0_API_KEY: "${RADARR_API_KEY}" # Radarr API key.
            UN_RADARR_0_URL: "http://radarr:7878" # Primary Radarr URL.
            UN_SONARR_0_API_KEY: "${SONARR_API_KEY}" # Sonarr API key.
            UN_SONARR_0_URL: "http://sonarr:8989" # Primary Sonarr URL.
        volumes:
            - downloads:/downloads # Root path to store downloaded files into.

    #############################################
    # mam-ip-helper: MyAnonaMouse IP updater.   #
    #############################################

    mam-ip-helper:
        <<: *defaults
        image: tyzen9/myanonamouse-ip-helper:latest
        container_name: mam-ip-helper
        network_mode: "service:gluetun" # Route all networking through Gluetun.
        read_only: true
        user: ${PUID}:${PGID}
        cap_drop:
            - ALL # Remove all permissions.
        depends_on:
            gluetun:
                condition: service_healthy # Require Gluetun to be healthy before connecting.
                restart: true
        environment:
            MAM_ID: "${MAM_ID}" # MyAnonaMouse session ID.
