---
name: media

include:
    - ./downloads/compose.yml # Media download tools.
    - ./management/compose.yml # Media management tools.

services:
    # Jellyfin: Media server.
    jellyfin:
        image: ghcr.io/jellyfin/jellyfin:10.11.0-rc8
        container_name: jellyfin
        hostname: jellyfin
        restart: unless-stopped
        user: ${PUID}:${PGID}
        devices:
            - /dev/dri:/dev/dri # Video device passthrough.
        environment:
            JELLYFIN_PublishedServerUrl: "${JELLYFIN_URL}" # Configures the published server URL.
        expose:
            - 8096/tcp # Web interface.
        networks:
            - caddy
        volumes:
            - /etc/localtime:/etc/localtime:ro # Local timezone mount.
            - jellyfin-cache:/cache
            - jellyfin-config:/config
            - media-library:/library:ro
        cap_drop:
            - ALL
        group_add:
            - ${RENDER_GID} # Required for video device support.
        healthcheck:
            test: "curl -f http://127.0.0.1:8096/health || exit 1"
        security_opt:
            - no-new-privileges:true

networks:
    caddy:
        external: true
        name: caddy-network

volumes:
    jellyfin-config:
        external: true
        name: jellyfin-config-volume # $ docker volume create jellyfin-config-volume
    jellyfin-cache:
        external: true
        name: jellyfin-cache-volume # $ docker volume create jellyfin-cache-volume
    media-library:
        name: media-library-bind
        driver_opts:
            device: "${MEDIA_LIBRARY_PATH}" # Root path to the media library.
            o: bind
            type: none
