services:
    sonarr:
        container_name: sonarr
        image: ghcr.io/11notes/sonarr:4
        read_only: true
        restart: unless-stopped
        tmpfs: /tmp:uid=1000,gid=1000 # Required for read-only images.
        environment:
            TZ: ${TZ}
        networks:
            - gluetun
            - media
        ports:
            - ${SONARR_PORT:-8989}:8989/tcp # Sonarr web interface.
        volumes:
            - downloads:/downloads # Root downloads volume.
            - media-library:/library # Root media library volume.
            - sonarr:/sonarr/etc # Configuration and data volume.
        security_opt:
            - no-new-privileges:true

volumes:
    sonarr:
        external: true
        name: sonarr-volume
