---
services:
    ###############################################################################
    # mam-ip-helper: Dynamically update MyAnonMouse session IP to match Gluetun.  #
    ##############################################################################

    mam-ip-helper:
        image: tyzen9/myanonamouse-ip-helper:latest
        container_name: mam-ip-helper
        network_mode: service:gluetun # Route all traffic through Gluetun.
        read_only: true
        restart: unless-stopped
        user: ${PUID}:${PGID}
        cap_drop:
            - ALL # Remove all permissions.
        depends_on:
            gluetun:
                condition: service_healthy
                restart: true
        environment:
            MAM_ID: "${MAM_ID}" # MyAnonaMouse session ID.
