services:
    mam-ip-helper:
        container_name: "mam-ip-helper"
        image: "tyzen9/myanonamouse-ip-helper:latest"
        network_mode: "service:gluetun" # Route all networking through Gluetun.
        read_only: "true"
        restart: "unless-stopped"
        security_opt: ["no-new-privileges:true"]
        environment:
            MAM_ID: "${MAM_ID}" # MyAnonaMouse ID.
        depends_on:
            gluetun:
                condition: "service_healthy" # Require Gluetun to be healthy before connecting.
                restart: "true"
