services:
    gluetun:
        container_name: gluetun
        image: ghcr.io/qdm12/gluetun:v3
        restart: unless-stopped
        devices:
            - /dev/net/tun:/dev/net/tun # TUN/TAP device passthrough.
        environment:
            BLOCK_MALICIOUS: off # Disable malicious content blocking; cuts memory usage significantly.
            FIREWALL_OUTBOUND_SUBNETS: ${FIREWALL_OUTBOUND_SUBNETS} # List of subnets able to access the container network.
            PGID: ${PGID}
            PORT_FORWARD_ONLY: ${PORT_FORWARD_ONLY} # If true, only connect to servers with port forwarding enabled.
            PUID: ${PUID}
            SERVER_COUNTRIES: ${SERVER_COUNTRIES} # List of countries provided by the VPN service provider to connect to.
            UPDATER_PERIOD: 24h # Updates the server list every 24 hours.
            VPN_PORT_FORWARDING: ${VPN_PORT_FORWARDING} # If set to on, enables port forwarding.
            VPN_SERVICE_PROVIDER: ${VPN_SERVICE_PROVIDER} # Sets the VPN service provider to use.
            VPN_TYPE: wireguard # Use Wireguard as the VPN protocol.
            WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY} # Base58 private Wireguard key provided by the VPN service provider.
        networks:
            - gluetun
        ports:
            - ${QBITTORRENT_PORT:-8080}:${QBITTORRENT_PORT:-8080} # qBittorrent web interface.
        volumes:
            - gluetun:/gluetun # Configuration and data volume.
        cap_add:
            - NET_ADMIN
        security_opt:
            - no-new-privileges:true

volumes:
    gluetun:
        name: gluetun-volume
        external: true
