services:
  syncthing:
    container_name: syncthing
    image: lscr.io/linuxserver/syncthing:latest
    env_file: ../../.env
    network_mode: host # Use host network mode.
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    environment:
      - PGID=${PGID} # Group ID to run under.
      - PUID=${PUID} # User ID to run under.
      - STGUIADDRESS= # Use default WebUI listener.
      - TZ=${TZ} # Timezone to run with.
      - UMASK=${UMASK} # Default umask permissions to set.
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    ports:
      - 8384:8384 # Lan Web UI.
      - 22000:22000 # LAN listening port, TCP.
      - 22000:22000/udp # LAN listening port, UDP.
      - 21027:21027/udp # LAN autodiscovery port, UDP.
    volumes:
      - ${ROOT_SYNCTHING_DIRECTORY}:/Sync # Syncthing root data directory.
