services:
  syncthing:
    container_name: syncthing
    image: lscr.io/linuxserver/syncthing:latest
    env_file: ../../.env
    restart: unless-stopped
    network_mode: host # Required for autodiscovery, needs ports 8384, 22000, and 21027/udp.
    environment:
      - PGID=${PGID} # Group ID to run the container under.
      - PUID=${PUID} # User ID to run the container under.
      - TZ=${TZ} # Timezone to run the container under.
      - UMASK=${UMASK} # Default UMASK permissions to set on newly created files.
    volumes:
      - ${SYNCTHING_DIRECTORY}/config:/config # Syncthing configuration directory.
      - ${SYNCTHING_DIRECTORY}/data:/Sync # Syncthing data directory.
    security_opt:
      - no-new-privileges:true # Do not allow privilege escalation.
