services:
  syncthing:
    container_name: syncthing
    image: lscr.io/linuxserver/syncthing:latest
    env_file: ../../.env
    network_mode: host # Use host network mode for local discovery.
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    labels:
      docker-volume-backup.stop-during-backup: true # Tells docker-volume-backup to stop during backups.
      docker-volume-backup.volume: /config # Tells docker-volume-backup to backup the /config volume.
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    volumes:
      - ${SYNCTHING_DATA_DIRECTORY}/config:/config # Syncthing's configuration and database.
      - ${SYNCTHING_DATA_DIRECTORY}/data:/Sync # Syncthing base data directory.
