services:
    prowlarr:
        container_name: "prowlarr"
        image: "lscr.io/linuxserver/prowlarr:latest"
        network_mode: "service:gluetun" # Route all networking through Gluetun.
        restart: "unless-stopped"
        security_opt: ["no-new-privileges:true"]
        depends_on:
            gluetun:
                condition: "service_healthy" # Require Gluetun to be healthy before connecting.
                restart: "true"
        environment:
            PGID: "${PGID}" # Group ID to run the container as.
            PUID: "${PUID}" # User ID to run the container as.
            TZ: "${TZ}" # Timezone to configure the container to use.
            UMASK: "${UMASK}" # Default umask permissions to apply to newly created files.
        healthcheck:
            interval: "1m"
            retries: "3"
            start_period: "15s"
            test: ["CMD", "curl", "-f", "http://127.0.0.1:9696/ping"]
            timeout: "3s"
        volumes:
            - "prowlarr:/config" # Configuration and data volume.

volumes:
    prowlarr:
        external: "true"
        name: "prowlarr-volume"
