services:
    bazarr:
        container_name: bazarr
        image: lscr.io/linuxserver/bazarr:1.5.2
        restart: unless-stopped
        environment:
            PGID: ${PGID}
            PUID: ${PUID}
            TZ: ${TZ}
            UMASK: ${UMASK}
        network_mode: service:gluetun # Route all networking through Gluetun.
        volumes:
            - bazarr:/config # Configuration and database volume.
            - media-library:/library # Root media library volume.
        depends_on:
            gluetun:
                condition: service_healthy # Require Gluetun to be healthy before connecting.
                restart: true
        security_opt:
            - no-new-privileges:true

volumes:
    bazarr:
        external: true
        name: bazarr-volume
