services:
    bazarr:
        container_name: "bazarr"
        image: "lscr.io/linuxserver/bazarr:latest"
        hostname: "bazarr"
        restart: "unless-stopped"
        security_opt: ["no-new-privileges:true"]
        environment:
            PGID: "${PGID}" # Group ID to run the container as.
            PUID: "${PUID}" # User ID to run the container as.
            TZ: "${TZ}" # Timezone to configure the container to use.
            UMASK: "${UMASK}" # Default umask permissions to apply to newly created files.
        networks:
            - "frontend" # Local frontend network.
            - "media" # Media stack network.
        ports:
            - "${BAZARR_PORT:-6767}:6767/tcp" # Local web interface.
        volumes:
            - "bazarr:/config" # Configuration and database volume.
            - "media-library:/library" # Root downloads volume.

volumes:
    bazarr:
        external: "true"
        name: "bazarr-volume"
    media-library:
        name: "media-library-volume"
        driver_opts:
            device: "${MEDIA_LIBRARY_PATH}" # Root media library path.
            o: "bind"
            type: "none"
