services:
    bazarr:
        container_name: bazarr
        image: lscr.io/linuxserver/bazarr:1.5.2
        restart: unless-stopped
        environment:
            PGID: ${PGID}
            PUID: ${PUID}
            TZ: ${TZ}
            UMASK: ${UMASK}
        networks:
            - media
        ports:
            - ${BAZARR_PORT:-6767}:6767/tcp # Bazarr web interface.
        volumes:
            - bazarr:/config # Configuration and database volume.
            - media-library:/library # Root media library volume.
        healthcheck:
            interval: 1m
            retries: 3
            start_period: 15s
            test: ["CMD", "curl", "-f", "http://localhost:6767/health"]
            timeout: 3s
        security_opt:
            - no-new-privileges:true

volumes:
    bazarr:
        external: true
        name: bazarr-volume
