services:
  socket-proxy:
    container_name: socket-proxy
    image: ghcr.io/11notes/socket-proxy:2
    env_file: ../../.env
    hostname: socket-proxy
    read_only: true
    restart: unless-stopped
    environment:
      - TZ=${TZ} # Timezone to run the container under.
      - SOCKET_PROXY_UID=${PUID} # User ID to run the container under.
      - SOCKET_PROXY_GID=${PGID} # Group ID to run the container under.
    ports:
      - 2375:2375/tcp # Docker socket proxy port access.
    volumes:
      - /run/docker.sock:/run/docker.sock:ro # Docker socket mount.
      - socket-proxy:/run/proxy # Socket proxy configuration/data volume.
    security_opt:
      - no-new-privileges:true
    user: 0:${DOCKER_UID} # Docker host user ID.
