services:
    flaresolverr:
        container_name: flaresolverr
        image: ghcr.io/flaresolverr/flaresolverr:v3.4.0
        restart: unless-stopped
        user: ${PUID}:${PGID}
        environment:
            TZ: ${TZ}
        networks:
            - media
        ports:
            - ${FLARESOLVERR_PORT:-8191}:8191/tcp # Flaresolverr API.
        healthcheck:
            interval: 1m
            retries: 3
            start_period: 15s
            test: ["CMD", "curl", "-f", "http://localhost:8191/health"]
            timeout: 3s
        security_opt:
            - no-new-privileges:true
