---
services:
    ###############################################################################
    # Flaresolverr: Bypass DDoS-Guard and Cloudflare captchas.                    #
    ##############################################################################

    flaresolverr:
        image: ghcr.io/flaresolverr/flaresolverr:v3.4.1
        container_name: flaresolverr
        user: ${PUID}:${PGID}
        network_mode: service:gluetun # Route all traffic through Gluetun.
        restart: unless-stopped
        depends_on:
            gluetun:
                condition: service_healthy
                restart: true
        environment:
            TZ: "${TZ}" # Configures the timezone to use.
        healthcheck:
            interval: 1m
            test: "curl -f http://127.0.0.1:8191/health || exit 1"
        security_opt:
            - no-new-privileges:true
