services:
    flaresolverr:
        container_name: flaresolverr
        image: "ghcr.io/flaresolverr/flaresolverr:latest"
        restart: "unless-stopped"
        user: "${PUID}:${PGID}"
        hostname: "flaresolverr"
        security_opt: ["no-new-privileges:true"]
        healthcheck:
            interval: "1m"
            retries: "3"
            start_period: "30s"
            test: ["CMD", "curl", "-f", "http://localhost:8191/health"]
            timeout: "3s"
        environment:
            TZ: "${TZ}" # Timezone to configure the container to use.
        networks:
            - "media" # Media stack network.
        ports:
            - "${FLARESOLVERR_PORT:-8191}:8191/tcp" # Local API.

networks:
    media:
        driver: "bridge"
        external: "true"
        name: "media-network"
