---
name: monitoring

# Default container options.
x-defaults: &defaults
    restart: unless-stopped
    security_opt:
        - no-new-privileges:true # Prevents privilege escalation.

services:
    #############################################
    # Uptime Kuma: Service uptime monitoring.   #
    #############################################

    uptime-kuma:
        <<: *defaults
        container_name: uptime-kuma
        image: ghcr.io/louislam/uptime-kuma:beta-rootless
        hostname: uptime-kuma
        depends_on:
            socket-proxy:
                condition: service_healthy # Wait for the Docker socket proxy to be healthy.
                restart: true
        labels:
            caddy: "${UPTIME_KUMA_URL}" # Tells Caddy to reverse proxy to the external Uptime Kuma URL.
            caddy.reverse_proxy: "uptime-kuma:3001" # Tells Caddy to reverse proxy internal traffic on port 3001.
            caddy.tls.ca: "https://acme.zerossl.com/v2/DV90" # Use ZeroSSL as the CA issuer.
            caddy.tls.dns: cloudflare $CLOUDFLARE_API_TOKEN # Use Cloudflare for DNS challenges.
            caddy.tls.protocols: "tls1.3" # Requires clients to support TLS 1.3.
        environment:
            DOCKER_HOST: "tcp://socket-proxy:2375" # Connect to the socket proxy.
            PGID: "${PGID}" # Group ID to run as.
            PUID: "${PUID}" # User ID to run as.
        networks:
            - caddy # External Caddy network; reverse proxied.
            - infra # Internal infra network.
        ports:
            - ${UPTIME_KUMA_PORT:-3001}:3001/tcp # Uptime Kuma web interface.
        volumes:
            - uptime-kuma:/app/data # Uptime Kuma configuration and database.

    #############################################
    # Dozzle: Docker compose log monitoring.    #
    #############################################

    dozzle:
        <<: *defaults
        container_name: dozzle
        image: ghcr.io/amir20/dozzle:latest
        hostname: dozzle
        environment:
            DOZZLE_ENABLE_ACTIONS: "true" # Enables container actions.
            DOZZLE_ENABLE_SHELL: "true" # Allows access to container shells.
        depends_on:
            socket-proxy:
                condition: service_healthy # Require socket-proxy to be healthy before starting.
                restart: true
        healthcheck:
            interval: 3s
            retries: 3
            start_period: 30s
            test: ["CMD", "/dozzle", "healthcheck"]
            timeout: 30s
        networks:
            - infra # Internal infra network.
        ports:
            - ${DOZZLE_PORT:-8082}:8080/tcp # Dozzle web interface.
        volumes:
            - dozzle:/data # Dozzle configuration and database.
            - /var/run/docker.sock:/var/run/docker.sock # Host Docker socket mount. SCARY!!!
